import type { CodeRule } from "../engines/code-rules.js";

export const API_SECURITY_RULES: CodeRule[] = [
  {
    id: "api-route-no-auth",
    severity: "high",
    category: "framework" as any,
    confidence: 70,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Express/Fastify route handler touches DB with no auth middleware or check",
    re: /\b(?:app|router|fastify)\s*\.\s*(?:get|post|put|delete|patch)\s*\(\s*['"`][^'"`]+['"`][\s\S]{0,400}?(?:db\s*\.|prisma\s*\.|await\s+User\.)/g,
    negativePattern: /(?:auth|getServerSession|currentUser|requireAuth|isAuthenticated|protect|withAuth|getAuth|jwt\s*\.\s*verify|passport\s*\.\s*authenticate)/,
    rationale: "A route handler that reads or writes data with no authentication middleware and no in-body auth check exposes the resource to anonymous callers.",
    fix: "Add auth middleware (e.g. requireAuth, passport.authenticate) before the handler, or call getServerSession / jwt.verify inside the handler before touching the database.",
  },
  {
    id: "api-excessive-data-exposure",
    severity: "high",
    category: "framework" as any,
    confidence: 80,
    owasp: "A03:2021 Sensitive Data Exposure",
    languages: ["javascript", "typescript"],
    title: "res.json() returns full user object (excessive data exposure)",
    re: /\bres\s*\.\s*json\s*\(\s*(?:user|req\.user|currentUser|loggedInUser)\b/g,
    rationale: "Returning the entire user record (or req.user) typically leaks password hashes, tokens, MFA secrets, and internal flags that the client never needs.",
    fix: "Project the response to a safe shape: res.json({ id: user.id, name: user.name, email: user.email }) or use a serializer / DTO.",
  },
  {
    id: "api-findmany-no-limit",
    severity: "medium",
    category: "framework" as any,
    confidence: 70,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "findMany() / findAll() with no take/limit (DoS + data exposure)",
    re: /\b(?:prisma|db)\.[\w]+\.find(?:Many|All)\s*\(\s*\{?[^})]*\}?\s*\)/g,
    negativePattern: /\b(?:take|limit)\s*:/,
    rationale: "Unbounded findMany / findAll loads every row into memory. Tables grow over time and one query eventually OOMs the process or returns megabytes of sensitive data.",
    fix: "Always pass a pagination cap: prisma.x.findMany({ take: 100, skip: cursor }) or db.x.findAll({ limit: 100 }).", // ironward-ignore
  },
  {
    id: "api-multer-no-file-validation",
    severity: "high",
    category: "framework" as any,
    confidence: 80,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "multer() configured with no fileFilter and no limits",
    re: /\bmulter\s*\(\s*\{[^}]*\}\s*\)/g,
    negativePattern: /(?:fileFilter|limits\s*:)/,
    rationale: "Without a fileFilter and limits, an attacker can upload arbitrary content types (e.g. .php, .html) of arbitrary size — disk-fill DoS and stored-XSS / RCE risk.",
    fix: "Pass both fileFilter (allowlist mime types) and limits ({ fileSize: 5 * 1024 * 1024 }) to multer().",
  },
  {
    id: "api-cors-credentials-wildcard",
    severity: "medium",
    category: "framework" as any,
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "cors() with origin: '*' and credentials: true",
    re: /\bcors\s*\(\s*\{[^}]*origin\s*:\s*['"]\*['"][^}]*credentials\s*:\s*true/g,
    rationale: "Wildcard origin combined with credentials is invalid per the spec and, where browsers tolerate it, lets any site read the response with cookies attached.",
    fix: "Set origin to an explicit allowlist of trusted hostnames when credentials: true. Never combine '*' with credentials.",
  },
  {
    id: "api-http-verb-tampering",
    severity: "medium",
    category: "framework" as any,
    confidence: 75,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Sensitive operation gated only by req.method check",
    re: /\bif\s*\(\s*req\s*\.\s*method\s*[!=]==?\s*['"](?:POST|GET|PUT|DELETE)['"]/g,
    rationale: "Dispatching write operations purely on req.method is brittle: HEAD requests can leak side-effecting GETs, and proxies / verb-tunneling middleware (X-HTTP-Method-Override) can flip the verb.",
    fix: "Use the framework router (app.post, app.put) so the verb is matched before the handler runs, and disable verb-override middleware unless required.",
  },
  {
    id: "api-unrestricted-resource-creation",
    severity: "high",
    category: "framework" as any,
    confidence: 65,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "POST endpoint creates DB records with no rate limiter nearby",
    re: /\bapp\s*\.\s*post\s*\(\s*['"`][^'"`]+['"`][\s\S]{0,200}?\b(?:create|insert|save|new)\s*\(/g,
    negativePattern: /(?:rateLimit|rate-limit|limiter|throttle)/,
    rationale: "A create endpoint with no rate limiting allows mass account / record creation — a common vector for spam, resource exhaustion, and credential-stuffing relays.",
    fix: "Apply express-rate-limit (or fastify-rate-limit) to the route, or add a per-IP / per-user limiter middleware before the handler.",
  },
];
