import type { CodeRule } from "../engines/code-rules.js";

export const CLERK_RULES: CodeRule[] = [
  {
    id: "clerk-public-routes-admin",
    severity: "critical",
    category: "clerk-auth",
    confidence: 90,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Clerk publicRoutes includes /api/admin",
    re: /publicRoutes\s*:\s*\[[^\]]*['"`]\/api\/admin/g,
    rationale: "Marking /api/admin as a public route bypasses Clerk auth and exposes admin endpoints to anonymous users.",
    fix: "Remove admin paths from publicRoutes and require an authenticated, role-checked user.",
  },
  {
    id: "clerk-public-routes-payment",
    severity: "critical",
    category: "clerk-auth",
    confidence: 90,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Clerk publicRoutes includes /api/payment",
    re: /publicRoutes\s*:\s*\[[^\]]*['"`]\/api\/payment/g,
    rationale: "Payment endpoints must always require an authenticated user. Listing them as public allows anyone to invoke them.",
    fix: "Remove /api/payment from publicRoutes.",
  },
  {
    id: "clerk-public-routes-billing",
    severity: "critical",
    category: "clerk-auth",
    confidence: 90,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Clerk publicRoutes includes /api/billing",
    re: /publicRoutes\s*:\s*\[[^\]]*['"`]\/api\/billing/g,
    rationale: "Billing endpoints expose subscription data and should never be reachable without auth.",
    fix: "Remove /api/billing from publicRoutes.",
  },
  {
    id: "clerk-public-routes-internal",
    severity: "critical",
    category: "clerk-auth",
    confidence: 90,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Clerk publicRoutes includes /api/internal",
    re: /publicRoutes\s*:\s*\[[^\]]*['"`]\/api\/internal/g,
    rationale: "Internal endpoints are typically privileged. Marking them public removes Clerk's auth gate.",
    fix: "Remove /api/internal from publicRoutes.",
  },
  {
    id: "clerk-public-routes-wildcard",
    severity: "critical",
    category: "clerk-auth",
    confidence: 95,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Clerk publicRoutes set to wildcard /(.*)",
    re: /publicRoutes\s*:\s*\[\s*['"`]\/?\(\.\*\)['"`]/g,
    rationale: "/(.*) makes every route public, defeating Clerk authentication entirely.",
    fix: "Replace with an explicit list of routes that should be reachable without auth (sign-in, marketing pages).",
  },
  {
    id: "clerk-middleware-public-everything",
    severity: "critical",
    category: "clerk-auth",
    confidence: 95,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "clerkMiddleware / authMiddleware with publicRoutes catch-all",
    re: /(?:clerkMiddleware|authMiddleware)\s*\(\s*\{[^}]*publicRoutes\s*:\s*\[[^\]]*['"`]\/?\*['"`]/g,
    rationale: "A wildcard publicRoutes entry disables auth on every route.",
    fix: "List specific public paths only.",
  },
  {
    id: "clerk-webhook-no-svix-verify",
    severity: "critical",
    category: "clerk-auth",
    confidence: 75,
    owasp: "A08:2021 Software and Data Integrity Failures",
    languages: ["javascript", "typescript"],
    title: "Clerk webhook handler missing svix signature verification",
    re: /(?:webhook|Webhook)[\s\S]{0,800}export\s+async\s+function\s+POST\s*\([\s\S]{0,800}\}(?<![\s\S]{0,800}(?:verifyWebhook|new\s+Webhook|svix))/g,
    rationale: "Without verifying the svix signature, an attacker can forge webhook payloads and trigger arbitrary side effects.",
    fix: "Use `new Webhook(secret).verify(payload, headers)` (svix) before trusting the body.",
  },
  {
    id: "clerk-getauth-no-userid-check",
    severity: "high",
    category: "clerk-auth",
    confidence: 60,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "getAuth() result used without checking userId",  // ironward-ignore
    re: /\bgetAuth\s*\([^)]*\)(?![\s\S]{0,200}(?:userId\s*===?\s*null|!\s*userId|if\s*\(\s*!?\s*userId))/g,
    rationale: "If userId is null, the request is unauthenticated. Skipping the null check means the handler runs for anonymous users.",
    fix: "After const { userId } = getAuth(req); return 401 when !userId before any sensitive operation.",
  },
  {
    id: "clerk-users-getlist-in-route",
    severity: "critical",
    category: "clerk-auth",
    confidence: 85,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "clerkClient.users.getUserList() exposed in API route without role check",
    re: /clerkClient\.users\.getUserList\s*\((?![\s\S]{0,300}(?:role|admin|isAdmin|orgRole))/g,
    rationale: "getUserList returns every user in the org. Calling it without a role check exposes the entire user directory.",
    fix: "Gate the call behind an admin role check (publicMetadata.role === 'admin' or similar).",
  },
  {
    id: "clerk-currentuser-result-unchecked",
    severity: "high",
    category: "clerk-auth",
    confidence: 55,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "currentUser() called but result.id never checked",  // ironward-ignore
    re: /\bcurrentUser\s*\(\s*\)(?![\s\S]{0,200}(?:\?\.id|\.id\s*===?\s*null|!\s*\w+|if\s*\(\s*!))/g,
    rationale: "currentUser() returns null for anonymous requests. Using the result without a null check leaks data to anonymous callers.",
    fix: "const user = await currentUser(); if (!user) return new Response('Unauthorized', { status: 401 });",
  },
  {
    id: "clerk-auth-await-no-check",
    severity: "high",
    category: "clerk-auth",
    confidence: 55,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "auth() result destructured but userId never validated",
    re: /const\s*\{\s*userId\s*\}\s*=\s*(?:await\s+)?auth\s*\(\s*\)\s*;(?![\s\S]{0,200}(?:!\s*userId|userId\s*===?\s*null|if\s*\(\s*!?\s*userId))/g,
    rationale: "userId from auth() is null when unauthenticated. Without a guard the handler proceeds anonymously.",
    fix: "Add `if (!userId) return ...` immediately after destructuring.",
  },
  {
    id: "clerk-public-route-regex-everything",
    severity: "critical",
    category: "clerk-auth",
    confidence: 90,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "createRouteMatcher includes /(.*) — matches everything",
    re: /createRouteMatcher\s*\(\s*\[\s*['"`]\/?\(\.\*\)['"`]/g,
    rationale: "A matcher of /(.*) matches every URL, so any auth-skipping logic that uses it skips auth on the entire app.",
    fix: "Provide specific patterns instead of /(.*).",
  },
  {
    id: "clerk-clerkclient-secret-in-client",
    severity: "critical",
    category: "clerk-auth",
    confidence: 80,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "CLERK_SECRET_KEY referenced in client component",
    re: /['"]use client['"][\s\S]{0,2000}CLERK_SECRET_KEY/g,
    rationale: "The Clerk secret key must never appear in a client component — it grants full admin access to the Clerk instance.",
    fix: "Move all calls that need CLERK_SECRET_KEY into server components or route handlers.",
  },
  {
    id: "clerk-organization-no-role-check",
    severity: "high",
    category: "clerk-auth",
    confidence: 55,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "auth().orgId used without checking orgRole",
    re: /\borgId\b(?![\s\S]{0,200}(?:orgRole|has\s*\(|hasRole))/g,
    rationale: "Treating any org member as authorized ignores Clerk's role system. Members may not be admins.",
    fix: "Check orgRole or has({ role: 'admin' }) before performing privileged org actions.",
  },
];
