import type { CodeRule } from "../engines/code-rules.js";

export const CLOUD_SECURITY_RULES: CodeRule[] = [
  {
    id: "cloud-aws-s3-public-acl",
    severity: "critical",
    category: "framework" as any,
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript", "yaml", "json", "terraform"],
    title: "S3 bucket / object ACL set to public-read or public-read-write",
    re: /\bACL\s*[:=]\s*['"](?:public-read|public-read-write)['"]/g,
    rationale: "A public ACL makes the bucket or object readable (and possibly writable) by anyone on the internet — the canonical S3 data leak.",
    fix: "Remove the ACL or set it to 'private'. Use bucket policies and signed URLs to grant scoped access instead.",
  },
  {
    id: "cloud-aws-iam-star-action",
    severity: "high",
    category: "framework" as any,
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["json", "yaml", "terraform"],
    title: "IAM policy with Action: \"*\" (full permissions)",
    re: /"Action"\s*:\s*"\*"/g,
    rationale: "Action: \"*\" grants every API call the principal can reach — the textbook over-privileged role. Compromise of the credential compromises the account.",
    fix: "Enumerate the specific actions required (e.g. [\"s3:GetObject\", \"s3:PutObject\"]). Use IAM Access Analyzer to derive a least-privilege policy from CloudTrail.",
  },
  {
    id: "cloud-aws-iam-star-resource",
    severity: "high",
    category: "framework" as any,
    confidence: 80,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["json", "yaml", "terraform"],
    title: "IAM policy with Resource: \"*\" applied to a non-trivial Action",
    re: /"Resource"\s*:\s*"\*"/g,
    rationale: "Resource: \"*\" applies the action to every resource in the account — the principal can reach buckets, tables, and secrets it should never touch.",
    fix: "Scope the resource to specific ARNs (e.g. arn:aws:s3:::my-bucket/*). Reserve Resource: \"*\" for actions that genuinely require it (e.g. iam:ListRoles).",
  },
  {
    id: "cloud-aws-rds-publicly-accessible",
    severity: "critical",
    category: "framework" as any,
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["json", "yaml", "terraform"],
    title: "RDS instance with PubliclyAccessible: true",  // ironward-ignore
    re: /\b(?:PubliclyAccessible|publicly_accessible)\b\s*"?\s*[:=]\s*(?:true|"true")\b/g,
    rationale: "A publicly-accessible RDS instance is reachable from the internet on its database port. Combined with weak passwords or default users, this is direct DB takeover.",
    fix: "Set PubliclyAccessible: false. Place the DB in a private subnet and reach it from the VPC (bastion host, VPN, or SSM session manager).",
  },
  {
    id: "cloud-aws-sg-open-ssh",
    severity: "critical",
    category: "framework" as any,
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["json", "yaml", "terraform"],
    title: "Security group exposes SSH (port 22) to 0.0.0.0/0",
    re: /\b(?:FromPort|from_port)\b\s*"?\s*[:=]\s*"?22\b[\s\S]{0,300}?['"]0\.0\.0\.0\/0['"]|['"]0\.0\.0\.0\/0['"][\s\S]{0,300}?\b(?:FromPort|from_port)\b\s*"?\s*[:=]\s*"?22\b/g,
    rationale: "Opening port 22 to 0.0.0.0/0 makes SSH reachable from every IP on the internet. Brute-force and exposure of CVEs in sshd become continuous risks.",
    fix: "Restrict SSH ingress to a corporate CIDR or a bastion's security group. Better: disable SSH and use SSM Session Manager (no inbound port).",
  },
  {
    id: "cloud-aws-sg-open-rdp",
    severity: "critical",
    category: "framework" as any,
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["json", "yaml", "terraform"],
    title: "Security group exposes RDP (port 3389) to 0.0.0.0/0",
    re: /\b(?:FromPort|from_port)\b\s*"?\s*[:=]\s*"?3389\b[\s\S]{0,300}?['"]0\.0\.0\.0\/0['"]|['"]0\.0\.0\.0\/0['"][\s\S]{0,300}?\b(?:FromPort|from_port)\b\s*"?\s*[:=]\s*"?3389\b/g,
    rationale: "RDP open to the world is the most common Windows compromise vector — credential brute-force and BlueKeep-class RCEs target it constantly.",
    fix: "Restrict RDP ingress to a VPN or bastion CIDR. Better: use AWS SSM Session Manager and remove the public RDP port entirely.",
  },
  {
    id: "cloud-gcp-bucket-allusers",
    severity: "critical",
    category: "framework" as any,
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["json", "yaml", "terraform", "javascript", "typescript"],
    title: "GCS bucket IAM grants allUsers or allAuthenticatedUsers",  // ironward-ignore
    re: /\b(?:allUsers|allAuthenticatedUsers)\b/g,  // ironward-ignore
    rationale: "allUsers is anonymous internet access; allAuthenticatedUsers is anyone with a Google account. Either binding makes the bucket effectively public.",  // ironward-ignore
    fix: "Remove the binding. Grant access to specific service accounts or groups, and use signed URLs for time-limited public reads.",
  },
  {
    id: "cloud-azure-storage-public-blob",
    severity: "high",
    category: "framework" as any,
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["json", "yaml", "terraform", "javascript", "typescript"],
    title: "Azure Storage container publicAccess set to Blob or Container",
    re: /\bpublicAccess\s*[:=]\s*['"](?:Blob|Container)['"]/g,
    rationale: "publicAccess Blob/Container makes blob contents (and optionally listing) anonymously readable. Sensitive data ends up indexed by crawlers.",
    fix: "Set publicAccess to 'None'. Use SAS tokens or Azure AD-authenticated clients for scoped access.",
  },
  {
    id: "cloud-aws-lambda-env-secrets",
    severity: "high",
    category: "framework" as any,
    confidence: 70,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["json", "yaml", "terraform"],
    title: "Lambda Environment.Variables contains a SECRET/KEY/PASSWORD/TOKEN entry",
    re: /\b(?:Environment|environment)\b[\s\S]{0,200}?\b(?:Variables|variables)\b[\s\S]{0,400}?\b\w*(?:SECRET|PASSWORD|TOKEN|API_KEY|PRIVATE_KEY)\w*\b\s*"?\s*[:=]/g,
    rationale: "Lambda env vars are visible to anyone with lambda:GetFunctionConfiguration and are written to CloudFormation / Terraform state in plaintext.",
    fix: "Store secrets in AWS Secrets Manager or SSM Parameter Store (SecureString) and fetch them at cold start. Reference them via IAM, not env vars.",
  },
];
