import type { CodeRule } from "../engines/code-rules.js";

export const ELECTRON_RULES: CodeRule[] = [
  {
    id: "electron-node-integration",
    severity: "critical",
    category: "framework" as any,
    confidence: 99,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Electron nodeIntegration: true enabled",
    re: /\bnodeIntegration\s*:\s*true/g,
    rationale: "Enabling nodeIntegration in renderer processes allows untrusted web content to execute arbitrary OS-level Node.js code.",
    fix: "Set `nodeIntegration: false`. Use `preload` scripts and `contextBridge` to expose specific functionality securely.",
  },
  {
    id: "electron-context-isolation-disabled",
    severity: "critical",
    category: "framework" as any,
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Electron contextIsolation: false disabled",
    re: /\bcontextIsolation\s*:\s*false/g,
    rationale: "Disabling contextIsolation allows the renderer's JavaScript to interfere with preload scripts and Electron's internal APIs.",
    fix: "Set `contextIsolation: true`. This is the default in modern Electron and should not be disabled.",
  },
  {
    id: "electron-remote-module",
    severity: "high",
    category: "framework" as any,
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Electron enableRemoteModule: true enabled",
    re: /\benableRemoteModule\s*:\s*true/g,
    rationale: "The remote module is deprecated and dangerous. It bridges the renderer and main process in a way that can be easily exploited.",
    fix: "Set `enableRemoteModule: false`. Use IPC (inter-process communication) via `ipcRenderer` and `ipcMain` instead.",
  },
  {
    id: "electron-sandbox-disabled",
    severity: "medium",
    category: "framework" as any,
    confidence: 85,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Electron sandbox: false disabled",
    re: /\bsandbox\s*:\s*false/g,
    rationale: "Disabling the Chromium sandbox reduces the security depth of the renderer process.",
    fix: "Enable the sandbox whenever possible, especially when loading untrusted remote content.",
  },
  {
    id: "electron-shell-open-external-user-input",
    severity: "high",
    category: "injection" as any,
    confidence: 80,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "Electron shell.openExternal with request input",
    re: /\bshell\s*\.\s*openExternal\s*\(\s*(?:req|request|params|searchParams|body|input)\./g,
    rationale: "Passing untrusted user input to `shell.openExternal` can allow attackers to execute local commands or open dangerous URIs.",
    fix: "Validate the URL protocol (allow only http: and https:) and hostname before calling `openExternal`.",
  },
  {
    id: "electron-webview-tag-enabled",
    severity: "medium",
    category: "framework" as any,
    confidence: 80,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Electron webviewTag: true enabled",
    re: /\bwebviewTag\s*:\s*true/g,
    rationale: "The <webview> tag has many security pitfalls. Electron recommends using <iframe> or `BrowserView` instead.",
    fix: "Disable `webviewTag` and use more secure alternatives for embedding remote content.",
  },
];
