import type { CodeRule } from "../engines/code-rules.js";

export const FIREBASE_RULES: CodeRule[] = [
  {
    id: "firebase-rules-allow-true",
    severity: "critical",
    category: "firebase",
    confidence: 95,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Firestore rules: allow read, write: if true",  // ironward-ignore
    re: /\ballow\s+(?:read\s*,\s*write|write\s*,\s*read|read|write)\s*:\s*if\s+true\b/g,
    rationale: "An `if true` rule grants every operation to every caller — your database is world-readable and world-writable.",
    fix: "Replace with rules that check request.auth.uid against the resource owner field.",
  },
  {
    id: "firebase-rules-auth-not-null",
    severity: "high",
    category: "firebase",
    confidence: 80,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Firestore rules allow any signed-in user (no ownership)",
    re: /\ballow\s+(?:read\s*,\s*write|write\s*,\s*read|read|write)\s*:\s*if\s+request\.auth\s*!=\s*null\s*;/g,
    rationale: "Checking only that the user is authenticated lets every signed-in user read or write every document.",
    fix: "Add an ownership check: `request.auth.uid == resource.data.userId` (and similar for create/update).",
  },
  {
    id: "firebase-storage-allow-read-true",
    severity: "high",
    category: "firebase",
    confidence: 90,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Firebase Storage rule: allow read: if true",  // ironward-ignore
    re: /\ballow\s+read\s*:\s*if\s+true\b/g,
    rationale: "Public read makes every uploaded file (potentially user PII / private documents) world-readable.",
    fix: "Restrict reads to the authenticated owner: `allow read: if request.auth.uid == resource.metadata.owner;`.",
  },
  {
    id: "firebase-storage-allow-write-true",
    severity: "critical",
    category: "firebase",
    confidence: 95,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Firebase Storage rule: allow write: if true",  // ironward-ignore
    re: /\ballow\s+write\s*:\s*if\s+true\b/g,
    rationale: "Public write lets anyone upload arbitrary content (malware hosting, abuse, billing exhaustion).",
    fix: "Require auth and validate path / size: `allow write: if request.auth != null && request.resource.size < 5 * 1024 * 1024;`.",
  },
  {
    id: "firebase-admin-in-client",
    severity: "critical",
    category: "firebase",
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "firebase-admin imported in a client component",
    re: /['"]use client['"][\s\S]{0,2000}from\s+['"]firebase-admin/g,
    rationale: "firebase-admin uses a service account that bypasses all security rules. Bundling it into the client exposes full admin access.",
    fix: "Use firebase-admin only in server code (route handlers, server actions, cloud functions). Use the regular firebase SDK in the browser.",
  },
  {
    id: "firebase-admin-import-browser-file",
    severity: "critical",
    category: "firebase",
    confidence: 70,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "firebase-admin imported in browser-targeted module",
    re: /import\s+[^;]*from\s+['"]firebase-admin['"]/g,
    rationale: "If this file is included in a client bundle, the admin SDK and its credentials reach the browser.",
    fix: "Restrict firebase-admin imports to server-only files. Verify webpack / Vite / Next config does not bundle them.",
  },
  {
    id: "firebase-admin-init-in-client",
    severity: "critical",
    category: "firebase",
    confidence: 85,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "admin.initializeApp() in a Next.js client component",
    re: /['"]use client['"][\s\S]{0,2000}admin\.initializeApp\s*\(/g,
    rationale: "Initializing firebase-admin in a client component leaks the service account into the browser bundle.",
    fix: "Move admin.initializeApp into a server-only module.",
  },
  {
    id: "firebase-service-account-public-env",
    severity: "critical",
    category: "firebase",
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Service account JSON path in NEXT_PUBLIC_/VITE_ env var",
    re: /\b(?:NEXT_PUBLIC_|VITE_|REACT_APP_)\w*SERVICE_ACCOUNT\w*\b/g,
    rationale: "Service account JSON grants full admin access. Public env vars ship the path (and often inlined contents) to the browser.",
    fix: "Use a server-only env var. Never reference service accounts from client code.",
  },
  {
    id: "firebase-rtdb-read-true",
    severity: "critical",
    category: "firebase",
    confidence: 95,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Realtime Database rule: .read: true",
    re: /"\.read"\s*:\s*"?\s*true\s*"?/g,
    rationale: "An RTDB read rule of true makes every node world-readable.",
    fix: "Restrict reads to the owner with `auth.uid === $userId`.",
  },
  {
    id: "firebase-rtdb-write-true",
    severity: "critical",
    category: "firebase",
    confidence: 95,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Realtime Database rule: .write: true",
    re: /"\.write"\s*:\s*"?\s*true\s*"?/g,
    rationale: "An RTDB write rule of true lets anyone overwrite any node, including admin / billing data.",
    fix: "Restrict writes to authenticated owners with explicit conditions.",
  },
  {
    id: "firebase-anonymous-signin",
    severity: "high",
    category: "firebase",
    confidence: 60,
    owasp: "A07:2021 Identification and Authentication Failures",
    languages: ["javascript", "typescript"],
    title: "signInAnonymously() used in a privileged flow",  // ironward-ignore
    re: /\bsignInAnonymously\s*\(/g,
    rationale: "Anonymous sign-in still produces an auth.uid that satisfies `request.auth != null` rules. Combined with weak rules this is effectively no auth at all.",
    fix: "Disable anonymous sign-in for sensitive flows, or pair with strict ownership rules and rate limiting.",
  },
  {
    id: "firebase-create-custom-token-client",
    severity: "critical",
    category: "firebase",
    confidence: 85,
    owasp: "A07:2021 Identification and Authentication Failures",
    languages: ["javascript", "typescript"],
    title: "createCustomToken called from client bundle",
    re: /['"]use client['"][\s\S]{0,2000}createCustomToken\s*\(/g,
    rationale: "createCustomToken requires admin credentials and lets the holder mint sessions for any uid. It must never run in the browser.",
    fix: "Mint custom tokens server-side only and return them over an authenticated channel.",
  },
  {
    id: "firebase-public-config-private-bucket",
    severity: "medium",
    category: "firebase",
    confidence: 50,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "FIREBASE_PRIVATE_KEY in NEXT_PUBLIC_ env",
    re: /\b(?:NEXT_PUBLIC_|VITE_|REACT_APP_)FIREBASE_PRIVATE_KEY\b/g,
    rationale: "The private key authenticates the service account. Shipping it to the browser is full account compromise.",
    fix: "Use a server-only env var.",
  },
  {
    id: "firebase-rules-resource-data-write",
    severity: "high",
    category: "firebase",
    confidence: 65,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Firestore write rule allows arbitrary fields (no validation)",
    re: /\ballow\s+(?:create|write|update)\s*:\s*if\s+request\.auth\s*!=\s*null\s*;/g,
    rationale: "Without validating `request.resource.data`, callers can write arbitrary fields including ones meant to be server-controlled (role, balance, etc.).",
    fix: "Use `request.resource.data.keys().hasOnly([...])` and field-level checks.",
  },
];
