import type { CodeRule } from "../engines/code-rules.js";

export const GO_RULES: CodeRule[] = [
  {
    id: "go-sql-sprintf",
    severity: "critical",
    category: "go",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["go"],
    title: "db.Query / db.Exec with fmt.Sprintf SQL string",
    re: /\bdb\s*\.\s*(?:Query|QueryRow|Exec|QueryContext|ExecContext)\s*\(\s*fmt\s*\.\s*Sprintf\s*\(/g,
    rationale: "Sprintf-formatted SQL embeds values directly into the query — classic injection bypassing the driver's parameter binding.",
    fix: "Use placeholders ($1, $2 for pgx; ? for mysql) and pass values as separate args: db.Query(\"SELECT ... WHERE id = $1\", id).",
  },
  {
    id: "go-sql-string-concat",
    severity: "critical",
    category: "go",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["go"],
    title: "db.Query with string concatenation",
    re: /\bdb\s*\.\s*(?:Query|QueryRow|Exec|QueryContext|ExecContext)\s*\(\s*"[^"]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b[^"]*"\s*\+\s*[A-Za-z_][\w]*/gi,
    rationale: "Concatenating user values into the SQL string is direct injection — placeholders are bound, strings are not.",
    fix: "Use parameterized placeholders and pass values as separate args.",
  },
  {
    id: "go-http-redirect-user",
    severity: "high",
    category: "open-redirect",
    confidence: 85,
    owasp: "A01:2021 Broken Access Control",
    languages: ["go"],
    title: "http.Redirect target taken directly from request query",
    re: /\bhttp\s*\.\s*Redirect\s*\(\s*[^,]+,\s*[^,]+,\s*r\s*\.\s*(?:URL\s*\.\s*Query\s*\(\s*\)\s*\.\s*Get|FormValue|PostFormValue)\s*\(/g,
    rationale: "Open redirect: the user crafts a phishing link that uses your domain and bounces to attacker.com.",
    fix: "Validate the target against an allowlist of internal paths (must start with '/' but not '//' and not contain a scheme).",
  },
  {
    id: "go-os-open-user",
    severity: "high",
    category: "path-traversal",
    confidence: 85,
    owasp: "A01:2021 Broken Access Control",
    languages: ["go"],
    title: "os.Open / os.OpenFile with request input",
    re: /\bos\s*\.\s*(?:Open|OpenFile)\s*\(\s*r\s*\.\s*(?:URL\s*\.\s*Query\s*\(\s*\)\s*\.\s*Get|FormValue|PostFormValue)\s*\(/g,
    rationale: "Reading a user-supplied path is directory traversal — leaks /etc/passwd, configs, secrets.",
    fix: "Resolve the path with filepath.Clean against a base dir and check the result starts with the base prefix.",
  },
  {
    id: "go-ioutil-readfile-user",
    severity: "high",
    category: "path-traversal",
    confidence: 85,
    owasp: "A01:2021 Broken Access Control",
    languages: ["go"],
    title: "ioutil.ReadFile / os.ReadFile with request input",
    re: /\b(?:ioutil|os)\s*\.\s*ReadFile\s*\(\s*r\s*\.\s*(?:URL\s*\.\s*Query\s*\(\s*\)\s*\.\s*Get|FormValue|PostFormValue)\s*\(/g,
    rationale: "Same path-traversal class as os.Open. Returns arbitrary file contents to the caller.",
    fix: "Resolve and confine the path inside a base directory before reading.",
  },
  {
    id: "go-exec-command-user",
    severity: "critical",
    category: "go",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["go"],
    title: "exec.Command with user input as the executable",
    re: /\bexec\s*\.\s*Command(?:Context)?\s*\(\s*r\s*\.\s*(?:URL\s*\.\s*Query\s*\(\s*\)\s*\.\s*Get|FormValue|PostFormValue)\s*\(/g,
    rationale: "Letting the request choose the binary is RCE — they can pick any executable on PATH.",
    fix: "Pin argv[0] to a fixed binary path. Validate user-supplied flags against an allowlist.",
  },
  {
    id: "go-exec-command-shell-c",
    severity: "critical",
    category: "go",
    confidence: 95,
    owasp: "A03:2021 Injection",
    languages: ["go"],
    title: "exec.Command(\"sh\", \"-c\", userInput) — shell injection",
    re: /\bexec\s*\.\s*Command(?:Context)?\s*\(\s*"(?:sh|bash|zsh|cmd)"\s*,\s*"(?:-c|\/c)"\s*,/g,
    rationale: "sh -c with any user-derived string is command injection via shell metachars.",
    fix: "Pass the program and each arg as separate strings: exec.Command(\"git\", \"log\", \"--\", path).",
  },
  {
    id: "go-template-html-bypass",
    severity: "high",
    category: "template-injection",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["go"],
    title: "template.HTML(userInput) bypasses html/template escaping",  // ironward-ignore
    re: /\btemplate\s*\.\s*HTML\s*\(\s*[A-Za-z_][\w]*\s*\)/g,
    rationale: "Casting a user string to template.HTML tells the engine \"this is already safe\" — the value is rendered without escaping. Direct XSS.",
    fix: "Render user values as strings (they get auto-escaped). Reserve template.HTML for trusted, server-generated markup.",
  },
  {
    id: "go-text-template-user-source",
    severity: "high",
    category: "template-injection",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["go"],
    title: "text/template Parse with user input as template source",
    re: /\btemplate\s*\.\s*New\s*\([^)]*\)\s*\.\s*Parse\s*\(\s*r\s*\.\s*(?:URL\s*\.\s*Query\s*\(\s*\)\s*\.\s*Get|FormValue|PostFormValue)\s*\(/g,
    rationale: "Parsing a user-controlled template lets the attacker call any method on the data context — info disclosure and sometimes RCE via FuncMap.",
    fix: "Load templates from disk only. Pass user data as values to ExecuteTemplate, never as the template body.",
  },
  {
    id: "go-weak-hash-import",
    severity: "medium",
    category: "weak-crypto",
    confidence: 70,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["go"],
    title: "Import of broken hash / cipher package (md5 / sha1 / des)", // ironward-ignore
    re: /\b(?:import\s*\(\s*[\s\S]{0,300}?|import\s+)["'](?:crypto\/md5|crypto\/sha1|crypto\/des|crypto\/rc4)["']/g, // ironward-ignore
    rationale: "MD5 and SHA-1 have practical collisions; DES and RC4 are broken ciphers. Importing them in new code is almost always wrong.",
    fix: "Use crypto/sha256 (or sha512) for hashing and crypto/aes with crypto/cipher.NewGCM for encryption.",
  },
  {
    id: "go-math-rand-secret",
    severity: "high",
    category: "weak-crypto",
    confidence: 85,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["go"],
    title: "math/rand used to generate token / secret / session / key",
    re: /\b(?:token|secret|key|session|nonce|otp|reset|verification)\w*\s*[:=][\s\S]{0,80}?\brand\s*\.\s*(?:Int|Intn|Int31|Int63|Read|Float)/gi, // ironward-ignore
    rationale: "math/rand is not a CSPRNG. Outputs are predictable from the seed; tokens generated this way are guessable.",
    fix: "Use crypto/rand: rand.Read(buf) (importing crypto/rand, not math/rand).",
  },
  {
    id: "go-tls-insecure-skip-verify",
    severity: "high",
    category: "insecure-protocol",
    confidence: 95,
    owasp: "A07:2021 Identification and Authentication Failures",
    languages: ["go"],
    title: "tls.Config{InsecureSkipVerify: true}",  // ironward-ignore
    re: /\bInsecureSkipVerify\s*:\s*true\b/g,
    rationale: "Disables certificate validation — any MITM with a self-signed cert can intercept the connection.",
    fix: "Remove the field. Add the custom CA via tls.Config{RootCAs: pool} if you need to trust an internal CA.",
  },
  {
    id: "go-http-client-no-timeout",
    severity: "medium",
    category: "ssrf",
    confidence: 70,
    owasp: "A04:2021 Insecure Design",
    languages: ["go"],
    title: "http.Client{} without a Timeout (SSRF window / slow-loris)",  // ironward-ignore
    re: /\b(?:http\s*\.\s*Client\s*\{\s*\}|&\s*http\s*\.\s*Client\s*\{\s*\})/g,
    rationale: "An http.Client with zero timeout will wait forever — a slow attacker server can pin every goroutine and exhaust the process.",
    fix: "Always set Timeout: 10 * time.Second (or appropriate) on http.Client. Use context.WithTimeout for per-request limits.",
  },
  {
    id: "go-bcrypt-low-cost",
    severity: "medium",
    category: "weak-crypto",
    confidence: 90,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["go"],
    title: "bcrypt.GenerateFromPassword with cost < 10",
    re: /\bbcrypt\s*\.\s*GenerateFromPassword\s*\([^,]+,\s*[0-9]\s*\)/g,
    rationale: "Bcrypt cost below 10 is brute-forceable on modern GPUs. The library default (currently 10) is the floor.",
    fix: "Use bcrypt.DefaultCost (10) at minimum. 12+ for high-value accounts. Re-evaluate as hardware changes.",
  },
  {
    id: "go-jwt-hardcoded-key",
    severity: "critical",
    category: "jwt",
    confidence: 88,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["go"],
    title: "jwt sign with a hardcoded byte literal as the key",
    re: /\b\.\s*SignedString\s*\(\s*\[\s*\]\s*byte\s*\(\s*"[^"]{1,40}"\s*\)\s*\)/g,
    rationale: "A hardcoded JWT signing key in source code can be extracted from the binary and used to forge any token.",
    fix: "Read the key from an env var at startup: os.Getenv(\"JWT_SECRET\"). Require it to be 32+ bytes.", // ironward-ignore
  },
  {
    id: "go-gorm-raw-concat",
    severity: "critical",
    category: "go",
    confidence: 88,
    owasp: "A03:2021 Injection",
    languages: ["go"],
    title: "gorm DB.Raw with string concatenation",
    re: /\b(?:db|tx|gormDB)\s*\.\s*Raw\s*\(\s*"[^"]*"\s*\+\s*[A-Za-z_][\w]*/g,
    rationale: "Concatenating into Raw bypasses gorm's parameterization — direct SQL injection.",
    fix: "Use placeholders: db.Raw(\"SELECT ... WHERE id = ?\", id).",
  },
  {
    id: "go-handler-no-maxbytesreader",
    severity: "medium",
    category: "ssrf",
    confidence: 60,
    owasp: "A04:2021 Insecure Design",
    languages: ["go"],
    title: "http handler reads request body without http.MaxBytesReader",
    re: /\b(?:io|ioutil)\s*\.\s*ReadAll\s*\(\s*r\s*\.\s*Body\s*\)/g,
    rationale: "Reading the body without a size cap lets an attacker exhaust memory by streaming gigabytes into a single request.",
    fix: "Wrap with http.MaxBytesReader(w, r.Body, 1<<20) before ReadAll.",
  },
  {
    id: "go-filepath-join-user",
    severity: "high",
    category: "path-traversal",
    confidence: 75,
    owasp: "A01:2021 Broken Access Control",
    languages: ["go"],
    title: "filepath.Join with request input but no containment check",
    re: /\bfilepath\s*\.\s*Join\s*\([^)]*r\s*\.\s*(?:URL\s*\.\s*Query\s*\(\s*\)\s*\.\s*Get|FormValue|PostFormValue)\s*\([^)]*\)\s*\)/g,
    rationale: "filepath.Join does not prevent traversal — a user value of '../../etc/passwd' produces a path outside the intended base.",
    fix: "After Join, call filepath.Clean and check strings.HasPrefix(resolved, base) before opening.",
  },
  {
    id: "go-cors-wildcard-with-credentials",
    severity: "high",
    category: "cors",
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["go"],
    title: "CORS Access-Control-Allow-Origin: * with Allow-Credentials true",
    re: /\bAccess-Control-Allow-Origin[^"]*"\s*,\s*"\*"\s*\)[\s\S]{0,400}?Access-Control-Allow-Credentials[^"]*"\s*,\s*"true"/g,
    rationale: "Browsers reject this combination, but if it ever works (custom client, header reflection bug), any origin can issue authenticated requests.",
    fix: "Echo back a specific origin from an allowlist; never combine '*' with credentials.",
  },
];
