import type { CodeRule } from "../engines/code-rules.js";

export const HONO_RULES: CodeRule[] = [
  {
    id: "hono-set-cookie-no-secure",
    severity: "high",
    category: "framework" as any,
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Hono setCookie without secure: true",
    re: /\bsetCookie\s*\([^)]*,\s*['"][^'"]+['"]\s*,\s*['"][^'"]+['"]\s*,\s*\{(?!.*secure\s*:\s*true)/g,
    rationale: "Setting a cookie without the Secure flag allows it to be sent over unencrypted HTTP, risking theft via MITM.",
    fix: "Add `secure: true` to the cookie options. Ensure your app is served over HTTPS.",
  },
  {
    id: "hono-set-cookie-no-httponly",
    severity: "medium",
    category: "framework" as any,
    confidence: 85,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Hono setCookie without httpOnly: true",
    re: /\bsetCookie\s*\([^)]*,\s*['"][^'"]+['"]\s*,\s*['"][^'"]+['"]\s*,\s*\{(?!.*httpOnly\s*:\s*true)/g,
    rationale: "Cookies without the httpOnly flag are accessible via client-side JavaScript, making them vulnerable to XSS-based theft.",
    fix: "Add `httpOnly: true` to the cookie options for sensitive session or auth tokens.",
  },
  {
    id: "hono-html-template-injection",
    severity: "critical",
    category: "injection" as any,
    confidence: 80,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "Hono raw() usage with request data",
    re: /\bhtml\s*`[\s\S]*?\${[\s\S]*?raw\s*\([\s\S]*?c\s*\.\s*(?:req|request)\s*\.\s*(?:query|param|json|parseBody)/g,
    rationale: "Hono's `html` helper automatically escapes values, but using `raw()` on request data bypasses this protection, leading to XSS.",
    fix: "Avoid `raw()` on untrusted input. If you must use it, sanitize the input with a library like DOMPurify first.",
  },
  {
    id: "hono-cors-wildcard",
    severity: "medium",
    category: "cors" as any,
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Hono CORS middleware with wildcard origin",
    re: /\bcors\s*\(\s*\{\s*origin\s*:\s*['"]\*['"]/g,
    rationale: "Wildcard CORS allows any origin to access your API. Combined with credentials, this can lead to data theft.",
    fix: "Restrict `origin` to a specific list of trusted domains.",
  },
  {
    id: "hono-bearer-auth-no-verify",
    severity: "high",
    category: "authentication" as any,
    confidence: 70,
    owasp: "A07:2021 Identification and Authentication Failures",
    languages: ["javascript", "typescript"],
    title: "Hono bearerAuth with simple string comparison",
    re: /\bbearerAuth\s*\(\s*\{\s*token\s*:\s*['"][^'"]+['"]\s*\}\s*\)/g,
    rationale: "Using a hardcoded static token for bearerAuth is less secure than dynamic validation (e.g., JWT).",
    fix: "Use a more robust authentication method or at least load the token from an environment variable.",
  },
];
