import type { CodeRule } from "../engines/code-rules.js";

export const INJECTION_RULES: CodeRule[] = [
  // --- NoSQL: MongoDB regex / function operators ---
  {
    id: "nosql-mongo-regex-user-input",
    severity: "high",
    category: "nosql",
    confidence: 80,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "MongoDB find() with $regex sourced from request input (ReDoS / regex injection)",
    re: /\$regex\s*:\s*(?:req|request|ctx|event)\s*\.\s*(?:body|params|query|headers)\s*\.[A-Za-z_$][\w$]*/g,
    rationale: "Letting users supply the $regex pattern allows catastrophic backtracking (ReDoS) and lets them rewrite the query semantics with anchors, alternation, or lookaheads.",
    fix: "Validate against a strict allowlist or escape the user input with a regex-escape helper, then anchor the resulting pattern. Cap the input length aggressively (<= 64 chars).",
  },
  {
    id: "nosql-mongo-aggregate-function",
    severity: "critical",
    category: "nosql",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "MongoDB aggregate() pipeline uses $function with request input",
    re: /\$function\s*:\s*\{[\s\S]{0,200}?(?:req|request|ctx|event)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "$function executes arbitrary JavaScript inside the database. User input here is direct server-side code injection.",
    fix: "Replace $function with native pipeline operators ($project, $cond, $switch). If you must compute, do it in app code on validated inputs.",
  },
  {
    id: "nosql-mongo-accumulator-user-js",
    severity: "critical",
    category: "nosql",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "MongoDB $accumulator stage with request-driven JS body",
    re: /\$accumulator\s*:\s*\{[\s\S]{0,300}?(?:req|request|ctx|event)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "$accumulator runs init/accumulate/merge JavaScript inside the database engine. Letting request input flow into those bodies is RCE on the DB host.",
    fix: "Use built-in accumulators ($sum, $avg, $push, $addToSet). If a custom accumulator is required, hardcode the JS bodies and pass only validated values via initArgs.",
  },

  // --- LDAP DN concatenation ---
  {
    id: "ldap-dn-concat-user-input",
    severity: "high",
    category: "framework",
    confidence: 80,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "LDAP distinguished name built by string concatenation with user input",
    re: /['"]\s*(?:uid|cn|ou|dc)\s*=['"]\s*\+\s*(?:req|request|ctx|user|input|username|email)\b/g,
    rationale: "Concatenating user-controlled values into an LDAP DN lets an attacker insert commas and equals signs to escape the intended subtree and target other branches of the directory.",
    fix: "Escape DN components with an LDAP DN escape helper (ldap-escape.dn or similar) and assemble the DN from constant fragments only.",
  },

  // --- XXE: parser configurations that leave entities enabled ---
  {
    id: "xxe-fast-xml-parser-no-entity-guard",
    severity: "high",
    category: "xxe",
    confidence: 70,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "fast-xml-parser configured with allowBooleanAttributes / preserveOrder but no entity guard",
    re: /new\s+XMLParser\s*\(\s*\{[^}]*(?:allowBooleanAttributes|preserveOrder)\s*:\s*true(?![^}]*processEntities\s*:\s*false)/g,
    rationale: "fast-xml-parser processes entities by default. Combined with looser parsing flags, attacker XML can declare external entities and read files or trigger SSRF.",
    fix: "Pass processEntities: false (and tagValueProcessor that rejects entity-like patterns) when parsing untrusted XML.",
  },
  {
    id: "xxe-libxmljs-no-noent-guard",
    severity: "high",
    category: "xxe",
    confidence: 80,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "libxmljs.parseXml called without noent: false / nonet: true",
    re: /\blibxmljs2?\s*\.\s*parseXml(?:String)?\s*\(\s*[^,)]+\s*(?:,\s*\{(?![^}]*noent\s*:\s*false)[^}]*\})?\s*\)/g,
    rationale: "Without { noent: false, nonet: true } libxmljs expands external entities and may fetch DTDs over the network — classic XXE.",
    fix: "Pass { noent: false, nonet: true, noblanks: true } and reject DOCTYPE declarations from untrusted sources.",
  },

  // --- SSTI: nunjucks / ejs / liquidjs ---
  {
    id: "ssti-nunjucks-render-string",
    severity: "high",
    category: "template-injection",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "nunjucks.renderString with request input as the template body",
    re: /\bnunjucks\s*\.\s*renderString\s*\(\s*(?:req|request|ctx|event)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "renderString compiles the first argument as a Nunjucks template. User-controlled template source allows {{constructor.constructor('return process')()}}-style RCE.",
    fix: "Render a template loaded from disk and pass user values as context variables. Never compile user input as a template.",
  },
  {
    id: "ssti-ejs-render-user-source",
    severity: "high",
    category: "template-injection",
    confidence: 88,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "ejs.render with template source from request input",
    re: /\bejs\s*\.\s*(?:render|compile)\s*\(\s*(?:req|request|ctx|event)\s*\.\s*(?:body|params|query|headers)\s*\.[A-Za-z_$][\w$]*/g,
    rationale: "EJS templates can run arbitrary JavaScript via <% %> blocks. User-supplied template strings are server-side code execution.",
    fix: "Load templates from a known directory by name only. Pass user data via the second argument (data object), never as the template source.",
  },
  {
    id: "ssti-liquidjs-parse-and-render",
    severity: "high",
    category: "template-injection",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "liquidjs parseAndRender with request input as template source",
    re: /\bparseAndRender\s*\(\s*(?:req|request|ctx|event)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "parseAndRender treats its first argument as a Liquid template. While Liquid is sandboxed, attacker templates can still leak context, trigger unbounded loops, and abuse custom filters.",
    fix: "Pre-register templates by name and only call render(name, data). Treat user input as data, never as template source.",
  },

  // --- Header / response injection ---
  {
    id: "crlf-writeHead-user-header-value",
    severity: "high",
    category: "header-injection",
    confidence: 80,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "res.writeHead headers object built from request input",
    re: /\bres\s*\.\s*writeHead\s*\(\s*\d+\s*,\s*\{[^}]*:\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)\s*\.[A-Za-z_$][\w$]*/g,
    rationale: "writeHead concatenates the headers object into the raw HTTP response. CR/LF in a user value splits the response and lets the attacker inject Set-Cookie or a fake second response.",
    fix: "Validate every header value with /^[\\w .,/:=+-]+$/, reject CR/LF, and prefer res.setHeader so Node performs additional checks.",
  },
  {
    id: "html-injection-error-message-concat",
    severity: "medium",
    category: "injection",
    confidence: 70,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "res.send concatenates HTML markup with err.message and request input",
    re: /\bres\s*\.\s*send\s*\(\s*['"`]<[^'"`]*['"`]\s*\+\s*err(?:or)?\s*\.\s*message\s*\+\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "Inlining err.message and request input into HTML markup is reflected XSS — error strings often echo the offending input verbatim.",
    fix: "Send JSON ({ error: 'message' }) or escape every interpolated value with an HTML escape helper before concatenating.",
  },

  // --- Email header injection (nodemailer) ---
  {
    id: "email-header-injection-nodemailer",
    severity: "high",
    category: "header-injection",
    confidence: 75,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "nodemailer message uses to/from from request body without validation",
    re: /\bsendMail\s*\(\s*\{[^}]*\b(?:to|from|cc|bcc|replyTo)\s*:\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)\s*\.[A-Za-z_$][\w$]*/g,
    rationale: "Unvalidated address fields allow attackers to add CR/LF and inject extra recipients, fake From: lines, or crafted Subject: headers — enabling spam relays and phishing.",
    fix: "Validate addresses with a strict RFC 5322 parser, reject CR/LF, and pin the From address to a server-controlled constant.",
  },

  // --- Command injection: shelljs ---
  {
    id: "shelljs-exec-template-literal",
    severity: "critical",
    category: "dangerous-function",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "shelljs.exec called with a template literal (string interpolation)",
    re: /\bshelljs?\s*\.\s*exec\s*\(\s*`[^`]*\$\{/g,
    rationale: "shelljs.exec runs the string through /bin/sh, so any interpolated value can break out with ; | && or backticks.",
    fix: "Use shell.exec(['cmd', arg1, arg2]) array form, or switch to execFile / spawn with the args array. Never interpolate into a shell string.",
  },

  // --- SQL injection variants not covered by sql-string-concat ---
  {
    id: "sequelize-raw-query-user-input",
    severity: "critical",
    category: "injection",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "sequelize.query with template literal containing request input",
    re: /\bsequelize\s*\.\s*query\s*\(\s*`[^`]*\$\{[^}]*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "sequelize.query interprets the string as raw SQL. Interpolating request input is direct SQL injection.",
    fix: "Use the replacements / bind parameter form: sequelize.query('SELECT ... WHERE id = $1', { bind: [id] }).",
  },
  {
    id: "knex-raw-user-input",
    severity: "high",
    category: "injection",
    confidence: 80,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "knex.raw built from a template literal with request input",
    re: /\bknex\s*\.\s*raw\s*\(\s*`[^`]*\$\{[^}]*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "knex.raw bypasses parameter binding. Interpolating user input into the raw SQL string is SQL injection.",
    fix: "Use bindings: knex.raw('SELECT * FROM t WHERE id = ?', [id]).",
  },

  // --- XPath injection ---
  {
    id: "xpath-select-user-input",
    severity: "high",
    category: "injection",
    confidence: 75,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "xpath.select with a query built from request input",
    re: /\bxpath\s*\.\s*select\s*\(\s*(?:`[^`]*\$\{[^}]*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)|['"][^'"]*['"]\s*\+\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers))/g,
    rationale: "Concatenating user input into an XPath expression lets an attacker change the predicate or escape the intended node set, returning data they should not see.",
    fix: "Use parameterised XPath via a library that supports variable bindings, or escape values with a strict XPath escape helper.",
  },
];
