import type { CodeRule } from "../engines/code-rules.js";

export const JAVA_RULES: CodeRule[] = [
  {
    id: "java-documentbuilderfactory-xxe",
    severity: "high",
    category: "xxe",
    confidence: 80,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["java"],
    title: "DocumentBuilderFactory used without disabling DOCTYPE / external entities",
    re: /\bDocumentBuilderFactory\s*\.\s*newInstance\s*\(\s*\)(?![\s\S]{0,800}?disallow-doctype-decl)/g,
    rationale: "Default DocumentBuilderFactory resolves DTDs and external entities — XXE lets attackers read local files and SSRF internal hosts.",
    fix: "factory.setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true) and disable external general/parameter entities.",
  },
  {
    id: "java-saxparserfactory-xxe",
    severity: "high",
    category: "xxe",
    confidence: 80,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["java"],
    title: "SAXParserFactory without external entity hardening",
    re: /\bSAXParserFactory\s*\.\s*newInstance\s*\(\s*\)(?![\s\S]{0,800}?(?:external-general-entities|disallow-doctype-decl))/g,
    rationale: "Default SAXParserFactory resolves external entities — same XXE class as DocumentBuilderFactory.",
    fix: "Set features: external-general-entities=false, external-parameter-entities=false, load-external-dtd=false, disallow-doctype-decl=true.",
  },
  {
    id: "java-xmlinputfactory-xxe",
    severity: "high",
    category: "xxe",
    confidence: 80,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["java"],
    title: "XMLInputFactory without IS_SUPPORTING_EXTERNAL_ENTITIES disabled",
    re: /\bXMLInputFactory\s*\.\s*newInstance\s*\(\s*\)(?![\s\S]{0,800}?IS_SUPPORTING_EXTERNAL_ENTITIES)/g,
    rationale: "StAX defaults allow external entity resolution. Same XXE class as DOM/SAX.",
    fix: "factory.setProperty(XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES, false) and IS_REPLACING_ENTITY_REFERENCES=false.",
  },
  {
    id: "java-objectinputstream-readobject",
    severity: "critical",
    category: "java",
    confidence: 95,
    owasp: "A08:2021 Software and Data Integrity Failures",
    languages: ["java"],
    title: "ObjectInputStream.readObject() — insecure Java deserialization",
    re: /\bObjectInputStream\s*\([^)]*\)[\s\S]{0,200}?\.\s*readObject\s*\(\s*\)/g,
    rationale: "Java serialization on untrusted bytes is RCE via gadget chains (commons-collections, Spring, etc.).",
    fix: "Replace with JSON or protobuf. If you must keep readObject, install a strict ObjectInputFilter that allowlists exact classes.",
  },
  {
    id: "java-statement-execute-concat",
    severity: "critical",
    category: "java",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["java"],
    title: "Statement.execute / executeQuery with string concatenation",
    re: /\bStatement\b[\s\S]{0,200}?\.\s*execute(?:Query|Update)?\s*\(\s*['"][^'"]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b[^'"]*['"]\s*\+/gi,
    rationale: "Concatenating user input into a Statement is classic SQL injection — Statement does not bind parameters.",
    fix: "Use PreparedStatement with ? placeholders and setString/setLong calls.",
  },
  {
    id: "java-preparedstatement-concat",
    severity: "high",
    category: "java",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["java"],
    title: "PreparedStatement built via string concatenation (defeats binding)",
    re: /\bprepareStatement\s*\(\s*['"][^'"]*['"]\s*\+\s*[A-Za-z_][\w]*/g,
    rationale: "Concatenating user input into the SQL passed to prepareStatement gives back a regular Statement-style injection — the parameter binding only protects ? placeholders.",
    fix: "Use ? placeholders for every value: prepareStatement(\"SELECT * FROM t WHERE id = ?\"); ps.setLong(1, id).",
  },
  {
    id: "java-file-user-input",
    severity: "high",
    category: "path-traversal",
    confidence: 85,
    owasp: "A01:2021 Broken Access Control",
    languages: ["java"],
    title: "new File(request.getParameter(...)) — path traversal",  // ironward-ignore
    re: /\bnew\s+File\s*\(\s*[^)]*\.\s*getParameter\s*\(/g,
    rationale: "File constructed from a request parameter lets attackers read or write outside the intended directory.",
    fix: "Resolve the path against a fixed base directory and call canonicalPath().startsWith(base) before opening.",
  },
  {
    id: "java-files-readallbytes-user",
    severity: "high",
    category: "path-traversal",
    confidence: 85,
    owasp: "A01:2021 Broken Access Control",
    languages: ["java"],
    title: "Files.readAllBytes(Paths.get(request.getParameter(...)))",  // ironward-ignore
    re: /\bFiles\s*\.\s*read(?:AllBytes|String|AllLines)\s*\(\s*Paths\s*\.\s*get\s*\([^)]*\.\s*getParameter\s*\(/g,
    rationale: "Reading arbitrary user-supplied paths leaks file contents (configs, /etc/passwd).",
    fix: "Resolve to a normalized path and confirm it stays inside an allowed base directory.",
  },
  {
    id: "java-runtime-exec-user",
    severity: "critical",
    category: "java",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["java"],
    title: "Runtime.getRuntime().exec(userInput)",  // ironward-ignore
    re: /\bRuntime\s*\.\s*getRuntime\s*\(\s*\)\s*\.\s*exec\s*\(\s*[A-Za-z_][\w]*\s*\)/g,
    rationale: "exec(String) splits on whitespace and runs the result. With user input you get command injection via shell metachars or argv tampering.",
    fix: "Use ProcessBuilder with an explicit String[] argv and never include user data as the executable. Validate args against an allowlist.",
  },
  {
    id: "java-processbuilder-user-cmd",
    severity: "high",
    category: "java",
    confidence: 80,
    owasp: "A03:2021 Injection",
    languages: ["java"],
    title: "ProcessBuilder with user input as command (sh-c style)",
    re: /\bnew\s+ProcessBuilder\s*\(\s*['"](?:sh|bash|cmd)['"]\s*,\s*['"](?:-c|\/c)['"]/g,
    rationale: "Invoking sh -c with any user-derived string is shell injection.",
    fix: "Pass the executable and each arg as separate strings to ProcessBuilder. Avoid sh -c entirely.",
  },
  {
    id: "java-md5-sha1-messagedigest",
    severity: "medium",
    category: "weak-crypto",
    confidence: 95,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["java"],
    title: "MessageDigest.getInstance with MD5 or SHA-1",
    re: /\bMessageDigest\s*\.\s*getInstance\s*\(\s*['"](?:MD5|SHA-?1)['"]/gi, // ironward-ignore
    rationale: "MD5 has practical collisions; SHA-1 is broken too. Not safe for signatures, integrity checks, or password hashing.",
    fix: "Use SHA-256 or SHA-3 for integrity. For passwords, use Argon2 (or BCrypt with cost >= 12) via a vetted library.",
  },
  {
    id: "java-cipher-weak-instance",
    severity: "high",
    category: "weak-crypto",
    confidence: 95,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["java"],
    title: "Cipher.getInstance with weak algorithm or ECB mode",
    re: /\bCipher\s*\.\s*getInstance\s*\(\s*['"](?:DES|DESede|RC4|RC2|Blowfish|AES\/ECB|DES\/[^"']*|AES)['"]/g,
    rationale: "DES/3DES/RC4 are broken. AES/ECB leaks block patterns. Cipher.getInstance(\"AES\") defaults to ECB on most JDKs.",
    fix: "Use \"AES/GCM/NoPadding\" with a 12-byte random IV per message and authenticated encryption.",
  },
  {
    id: "java-securerandom-setseed-constant",
    severity: "high",
    category: "weak-crypto",
    confidence: 80,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["java"],
    title: "SecureRandom.setSeed with Date / constant (predictable seed)",
    re: /\bSecureRandom\b[\s\S]{0,200}?\.\s*setSeed\s*\(\s*(?:new\s+Date\s*\(|System\s*\.\s*currentTimeMillis\s*\(|\d+L?)/g,
    rationale: "Calling setSeed with Date.getTime() or a constant overrides the OS entropy source; outputs become predictable.",
    fix: "Do not call setSeed. SecureRandom seeds itself from /dev/urandom or the OS CSPRNG.",
  },
  {
    id: "java-random-for-secret",
    severity: "high",
    category: "weak-crypto",
    confidence: 80,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["java"],
    title: "java.util.Random used for tokens / session IDs",
    re: /\bnew\s+Random\s*\(\s*[^)]*\)\s*;[\s\S]{0,200}?\b(?:token|session|nonce|otp|reset|verification)/gi,
    rationale: "java.util.Random is a 48-bit LCG — its outputs are predictable. Tokens generated this way are guessable.",
    fix: "Use SecureRandom (or KeyGenerator for keys). java.util.Random is for non-security uses only.",
  },
  {
    id: "java-hostnameverifier-allow-all",
    severity: "high",
    category: "insecure-protocol",
    confidence: 90,
    owasp: "A07:2021 Identification and Authentication Failures",
    languages: ["java"],
    title: "Hostname verifier that returns true for all hosts",
    re: /\bverify\s*\(\s*[^)]*\)\s*\{\s*return\s+true\s*;/g,
    rationale: "An always-true HostnameVerifier disables hostname pinning; any cert valid for any name passes — MITM trivially defeats TLS.",
    fix: "Remove the custom verifier. Use the default HttpsURLConnection.getDefaultHostnameVerifier().",
  },
  {
    id: "java-trust-all-certs",
    severity: "critical",
    category: "insecure-protocol",
    confidence: 95,
    owasp: "A07:2021 Identification and Authentication Failures",
    languages: ["java"],
    title: "TrustManager that accepts all certificates",
    re: /\bcheckServerTrusted\s*\(\s*[^)]*\)\s*\{\s*\}/g,
    rationale: "An empty checkServerTrusted accepts any cert chain — TLS becomes obfuscation. Used in countless leaked Android/Java apps.",
    fix: "Remove the custom TrustManager. Trust the platform default; pin specific CAs only when you have a clear pinning strategy.",
  },
  {
    id: "java-jndi-user-input",
    severity: "critical",
    category: "java",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["java"],
    title: "JNDI lookup with user input (Log4Shell-class)",
    re: /\b(?:InitialContext|Context|ic)\s*\.\s*lookup\s*\(\s*[^)]*\.\s*getParameter\s*\(/g,
    rationale: "JNDI lookup against an attacker-controlled URI fetches and instantiates a remote object — RCE (CVE-2021-44228 was this class of bug).",
    fix: "Never pass user data to JNDI lookups. Pin the lookup name to a constant resource string.",
  },
  {
    id: "java-hibernate-createquery-concat",
    severity: "critical",
    category: "java",
    confidence: 88,
    owasp: "A03:2021 Injection",
    languages: ["java"],
    title: "Hibernate Session.createQuery with string concatenation",
    re: /\b(?:session|em|entityManager)\s*\.\s*createQuery\s*\(\s*['"][^'"]*['"]\s*\+\s*[A-Za-z_][\w]*/g,
    rationale: "Concatenating into HQL is HQL injection — attackers can read or modify any entity.",
    fix: "Use named parameters: createQuery(\"FROM User WHERE name = :name\").setParameter(\"name\", name).",
  },
  {
    id: "java-secretkeyspec-hardcoded",
    severity: "critical",
    category: "java",
    confidence: 85,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["java"],
    title: "SecretKeySpec built from a hardcoded literal byte array",
    re: /\bnew\s+SecretKeySpec\s*\(\s*(?:['"][^'"]+['"]\s*\.\s*getBytes\s*\(|new\s+byte\s*\[\s*\]\s*\{\s*(?:0[xX][0-9a-fA-F]+|\d+)\s*,)/g,
    rationale: "Hardcoded keys can be extracted from the JAR. Anyone who decompiles the app can decrypt every message ever encrypted with it.",
    fix: "Load the key from a KeyStore, KMS, or env var at runtime. Never bake key bytes into source.",
  },
  {
    id: "java-spring-csrf-disable",
    severity: "high",
    category: "java",
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["java"],
    title: "Spring Security CSRF disabled",
    re: /\.\s*csrf\s*\(\s*\)\s*\.\s*disable\s*\(/g,
    rationale: "Disabling CSRF protection on a session-cookie-authenticated app exposes every state-changing endpoint to cross-site request forgery.",
    fix: "Keep CSRF enabled. Disable only for stateless APIs that authenticate via Authorization header (token-based).",
  },
];
