import type { CodeRule } from "../engines/code-rules.js";

export const LOGGING_SECURITY_RULES: CodeRule[] = [
  {
    id: "log-sensitive-request-body",
    severity: "high",
    category: "logging" as any,
    confidence: 70,
    owasp: "A09:2021 Security Logging and Monitoring Failures",
    languages: ["javascript", "typescript"],
    title: "logger / console call that logs req.body directly",
    re: /\b(?:logger|log|console)\s*\.\s*(?:log|info|debug|warn|error|trace)\s*\([^)]{0,200}\breq\s*\.\s*body\b/g,
    rationale: "POST/PUT bodies routinely contain passwords, card numbers, OTPs, etc. Writing them to logs creates a long-lived secondary copy outside encryption boundaries.",
    fix: "Log a redacted summary (`{ ...req.body, password: '[redacted]' }`) or use a logger with a field-redaction transformer.", // ironward-ignore
  },
  {
    id: "log-sensitive-headers",
    severity: "high",
    category: "logging" as any,
    confidence: 80,
    owasp: "A09:2021 Security Logging and Monitoring Failures",
    languages: ["javascript", "typescript"],
    title: "Logging req.headers.authorization or req.headers.cookie",
    re: /\b(?:logger|log|console)\s*\.\s*(?:log|info|debug|warn|error|trace)\s*\([^)]{0,200}\breq\s*\.\s*headers\s*\.\s*(?:authorization|cookie)\b/g,
    rationale: "Authorization headers and cookies are bearer credentials. Logged tokens become live credentials for anyone with log access.",
    fix: "Strip `authorization` and `cookie` from log payloads (most loggers ship a redaction list — pino's `redact` option, etc.).",
  },
  {
    id: "log-pii-user-object",
    severity: "medium",
    category: "logging" as any,
    confidence: 55,
    owasp: "A09:2021 Security Logging and Monitoring Failures",
    languages: ["javascript", "typescript"],
    title: "Logging the full user object (likely PII)",
    re: /\b(?:console|logger|log)\s*\.\s*(?:log|info|debug|warn|error|trace)\s*\(\s*user\s*\)/g,
    rationale: "User objects typically include email, phone, hashed password, and PII fields. Whole-object logging is a GDPR / SOC2 finding.",
    fix: "Log `user.id` only, or a curated subset (`{ id, role }`). Centralize via a `safeUser()` helper.",
  },
  {
    id: "log-error-stack-to-client",
    severity: "high",
    category: "logging" as any,
    confidence: 90,
    owasp: "A09:2021 Security Logging and Monitoring Failures",
    languages: ["javascript", "typescript"],
    title: "Sending err.stack / err.message back in HTTP response",
    re: /\bres\s*\.\s*(?:json|send|status\s*\(\s*\d+\s*\)\s*\.\s*(?:json|send))\s*\(\s*\{?[^)]{0,200}\berr(?:or)?\s*\.\s*(?:stack|message)\b/g,
    rationale: "Stack traces leak file paths, ORM internals, and library versions — direct intel for attackers.",
    fix: "Return a generic error message and a correlation id; log the stack server-side keyed by that id.",
  },
  {
    id: "log-missing-audit-admin-op",
    severity: "medium",
    category: "logging" as any,
    confidence: 50,
    owasp: "A09:2021 Security Logging and Monitoring Failures",
    languages: ["javascript", "typescript"],
    title: "Destructive DB op without an adjacent audit log call",
    // db.<table>.delete( or User.deleteOne( with no logger/audit call within the next ~200 chars.  // ironward-ignore
    re: /\b(?:db|prisma|knex|models?)\s*\.\s*\w+\s*\.\s*delete\s*\(|\b(?:User|Account|Order|Invoice|Session)\s*\.\s*deleteOne\s*\(/g,
    rationale: "Destructive admin operations without an audit trail mean you cannot answer 'who deleted this?' during incident response.",
    fix: "Emit `audit.log({ action, actorId, target, ts })` (or your equivalent) immediately before/after the delete.",
    negativePattern: /\b(?:audit|logger|console|log)\s*\.\s*\w+\s*\(/,
  },
];
