import type { CodeRule } from "../engines/code-rules.js";

export const MOBILE_SECURITY_RULES: CodeRule[] = [
  {
    id: "rn-asyncstorage-sensitive",
    severity: "high",
    category: "react" as any,
    confidence: 85,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["javascript", "typescript"],
    title: "AsyncStorage.setItem with key that looks like a secret",
    re: /\bAsyncStorage\s*\.\s*setItem\s*\(\s*['"`][^'"`]*(?:token|password|secret|auth|jwt|key)[^'"`]*['"`]/gi,
    rationale: "AsyncStorage on React Native is plaintext and easily extractable on rooted/jailbroken devices and from device backups.",
    fix: "Use `react-native-keychain` (iOS Keychain / Android Keystore) or `expo-secure-store` for any auth token, password, or API key.",
  },
  {
    id: "rn-fetch-http",
    severity: "high",
    category: "react" as any,
    confidence: 85,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["javascript", "typescript"],
    title: "fetch() to an http:// URL (cleartext) in mobile code",
    re: /\bfetch\s*\(\s*['"`]http:\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0)[^'"`]+['"`]/g,
    rationale: "Cleartext HTTP on a mobile network is trivially MITM'd (rogue Wi-Fi, captive portal). iOS ATS and Android cleartext policy block this for a reason.",
    fix: "Use https:// everywhere. If you genuinely need cleartext for development, gate it on `__DEV__` and never ship the build.",
  },
  {
    id: "rn-expo-config-secret",
    severity: "critical",
    category: "react" as any,
    confidence: 80,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Expo app.config.js extra: { ... } contains apiKey/secret/token",
    re: /\bextra\s*:\s*\{[\s\S]{0,400}?\b(?:apiKey|api_key|secret|token|password|privateKey)\s*:\s*['"`][^'"`]+['"`]/gi,
    rationale: "Anything under `extra` in app.config.* is bundled into the app binary and readable by anyone who unzips the .ipa / .apk.",
    fix: "Move secrets to a server endpoint and fetch them with an authenticated session. For build-time public config, prefix with `EXPO_PUBLIC_` only when truly public.",
  },
  {
    id: "rn-debug-mode-skip",
    severity: "high",
    category: "react" as any,
    confidence: 80,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "if (__DEV__) return; — security check skipped in dev",  // ironward-ignore
    re: /\bif\s*\(\s*__DEV__\s*\)\s*(?:return\b|\{\s*return\b)/g,
    rationale: "Bypassing auth, cert-pinning, or signature checks in dev builds is fine — until a dev build leaks (TestFlight, internal track) and turns into a production-equivalent bypass.",
    fix: "Make the check unconditional. Use a separate fixture/mock layer for dev rather than disabling production controls.",
  },
  {
    id: "rn-react-native-keys-bundled",
    severity: "high",
    category: "react" as any,
    confidence: 75,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Constants.manifest.extra read of a secret-shaped key",
    re: /\bConstants\s*\.\s*(?:manifest|expoConfig)\s*(?:\.\s*extra)?\s*\.\s*\w*(?:apiKey|api_key|secret|token|password|privateKey)\w*/gi,
    rationale: "Reading from `Constants.manifest.extra` returns a value baked into the app bundle at build time — anyone with the binary can extract it.",
    fix: "Fetch the secret from your backend after authentication, or rotate to a public-by-design token (e.g. publishable key) if it must live client-side.",
  },
];
