import type { CodeRule } from "../engines/code-rules.js";

export const NEXTJS_RULES: CodeRule[] = [
  {
    id: "nextjs-public-secret-env",
    severity: "critical",
    category: "nextjs",
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "NEXT_PUBLIC_SECRET env var leaks server secret to the browser bundle", // ironward-ignore
    re: /\bNEXT_PUBLIC_SECRET\b/g, // ironward-ignore
    rationale: "Any env var prefixed with NEXT_PUBLIC_ is inlined into the client bundle and visible to every visitor.",
    fix: "Rename the variable to drop NEXT_PUBLIC_ and read it only from server code (route handlers, server actions, getServerSideProps).",
  },
  {
    id: "nextjs-public-api-key-env",
    severity: "critical",
    category: "nextjs",
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "NEXT_PUBLIC_API_KEY exposes a server API key in the client", // ironward-ignore
    re: /\bNEXT_PUBLIC_API_KEY\b/g, // ironward-ignore
    rationale: "Public env vars ship to every browser. Anyone can extract the key from devtools or the JS bundle.",
    fix: "Move the key to a non-public env var and proxy calls through a server route.",
  },
  {
    id: "nextjs-public-private-env",
    severity: "critical",
    category: "nextjs",
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "NEXT_PUBLIC_PRIVATE_* env var contradicts itself",  // ironward-ignore
    re: /\bNEXT_PUBLIC_PRIVATE\w*\b/g,
    rationale: "Naming an env var both PUBLIC and PRIVATE is a clear sign a server secret was accidentally exposed to the bundle.",
    fix: "Rename to drop NEXT_PUBLIC_ and only read from server-side code.",
  },
  {
    id: "nextjs-public-password-env",
    severity: "critical",
    category: "nextjs",
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "NEXT_PUBLIC_PASSWORD env var ships a credential to clients", // ironward-ignore
    re: /\bNEXT_PUBLIC_PASSWORD\b/g, // ironward-ignore
    rationale: "Any visitor can inspect the JS bundle and read the password.", // ironward-ignore
    fix: "Drop the NEXT_PUBLIC_ prefix and read the value only on the server.",
  },
  {
    id: "nextjs-public-database-url",
    severity: "critical",
    category: "nextjs",
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "NEXT_PUBLIC_DATABASE_URL leaks DB credentials to the browser",  // ironward-ignore
    re: /\bNEXT_PUBLIC_DATABASE_URL\b/g,
    rationale: "Database connection strings include username and password. Exposing them via NEXT_PUBLIC_ gives anyone direct DB access.", // ironward-ignore
    fix: "Use DATABASE_URL (no NEXT_PUBLIC_ prefix). Only access it from server-side code.",
  },
  {
    id: "nextjs-public-stripe-secret",
    severity: "critical",
    category: "nextjs",
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "NEXT_PUBLIC_STRIPE_SECRET exposes Stripe secret key in the client",  // ironward-ignore
    re: /\bNEXT_PUBLIC_STRIPE_SECRET\w*\b/g,
    rationale: "The Stripe secret key allows full account takeover (refunds, transfers, customer data). It must never reach the browser.",
    fix: "Use STRIPE_SECRET_KEY server-side only. Use NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY for the client.",
  },
  {
    id: "nextjs-pages-handler-no-auth",
    severity: "high",
    category: "nextjs",
    confidence: 70,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "pages/api handler has no auth check",
    re: /export\s+default\s+(?:async\s+)?function\s+handler\s*\([^)]*\)\s*\{(?:(?!getServerSession|auth\s*\(|clerk|currentUser|getToken|verifyJwt)[\s\S]){0,600}\}/g,
    rationale: "An API route with no session/token check is reachable by anyone on the internet.",
    fix: "Call getServerSession / auth() / currentUser() / verify the JWT at the top of the handler and 401 unauthenticated requests.",  // ironward-ignore
  },
  {
    id: "nextjs-app-route-get-no-auth",
    severity: "high",
    category: "nextjs",
    confidence: 65,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "App Router GET handler with no auth check",
    re: /export\s+async\s+function\s+GET\s*\([^)]*\)\s*\{(?:(?!getServerSession|auth\s*\(|clerk|currentUser|getToken|verifyJwt)[\s\S]){0,600}\}/g,
    rationale: "A route handler that never checks the session is open to the world.",
    fix: "Call auth() / getServerSession() / currentUser() and return 401 if the user is not signed in.",  // ironward-ignore
  },
  {
    id: "nextjs-app-route-post-no-auth",
    severity: "high",
    category: "nextjs",
    confidence: 70,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "App Router POST handler with no auth check",
    re: /export\s+async\s+function\s+POST\s*\([^)]*\)\s*\{(?:(?!getServerSession|auth\s*\(|clerk|currentUser|getToken|verifyJwt)[\s\S]){0,600}\}/g,
    rationale: "A mutating route with no auth check lets anyone trigger writes.",
    fix: "Authenticate the caller before performing any mutation.",
  },
  {
    id: "nextjs-app-route-put-no-auth",
    severity: "high",
    category: "nextjs",
    confidence: 70,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "App Router PUT handler with no auth check",
    re: /export\s+async\s+function\s+PUT\s*\([^)]*\)\s*\{(?:(?!getServerSession|auth\s*\(|clerk|currentUser|getToken|verifyJwt)[\s\S]){0,600}\}/g,
    rationale: "Updates without authentication allow tampering by anyone.",
    fix: "Authenticate the caller and authorize ownership of the target resource.",
  },
  {
    id: "nextjs-app-route-delete-no-auth",
    severity: "high",
    category: "nextjs",
    confidence: 75,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "App Router DELETE handler with no auth check",
    re: /export\s+async\s+function\s+DELETE\s*\([^)]*\)\s*\{(?:(?!getServerSession|auth\s*\(|clerk|currentUser|getToken|verifyJwt)[\s\S]){0,600}\}/g,
    rationale: "Deletes without authentication let anyone wipe data.",
    fix: "Authenticate the caller and authorize ownership before deleting.",
  },
  {
    id: "nextjs-server-action-no-auth",
    severity: "high",
    category: "nextjs",
    confidence: 65,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "'use server' Server Action with no auth check",
    re: /['"]use server['"][\s\S]{0,1200}export\s+(?:async\s+)?function\s+\w+\s*\([^)]*\)\s*\{(?:(?!getServerSession|auth\s*\(|clerk|currentUser|getToken|verifyJwt)[\s\S]){0,600}\}/g,
    rationale: "Server Actions are remotely invokable RPC endpoints. Without an auth check they are equivalent to a public mutation API.",
    fix: "Call auth() / getServerSession() at the top of the action and throw if the user is not signed in.",
  },
  {
    id: "nextjs-dangerously-set-inner-html-req",
    severity: "critical",
    category: "nextjs",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "dangerouslySetInnerHTML fed with request data",
    re: /dangerouslySetInnerHTML\s*=\s*\{\s*\{\s*__html\s*:\s*[^}]*\b(?:req|request|params|searchParams|router\.query|useSearchParams)\b[^}]*\}\s*\}/g,
    rationale: "Rendering raw user-controlled HTML enables stored / reflected XSS.",
    fix: "Sanitize with DOMPurify (or render as text) before injecting. Prefer not using dangerouslySetInnerHTML at all.",
  },
  {
    id: "nextjs-dangerously-set-inner-html-search-params",
    severity: "critical",
    category: "nextjs",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "dangerouslySetInnerHTML rendering searchParams",
    re: /dangerouslySetInnerHTML\s*=\s*\{\s*\{\s*__html\s*:\s*searchParams[^}]*\}\s*\}/g,
    rationale: "URL query parameters are attacker-controlled. Injecting them as HTML triggers reflected XSS.",
    fix: "Render values as text or sanitize with DOMPurify before passing to __html.",
  },
  {
    id: "nextjs-edge-leak-process-env",
    severity: "critical",
    category: "nextjs",
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Edge / route handler leaks process.env in JSON response",
    re: /NextResponse\.json\s*\(\s*\{[^}]*process\.env\.\w+/g,
    rationale: "Returning process.env values in the response body exposes secrets, API keys, and connection strings to whoever calls the route.",
    fix: "Never echo process.env into a response. Return only the data the caller needs.",
  },
  {
    id: "nextjs-res-json-process-env",
    severity: "critical",
    category: "nextjs",
    confidence: 85,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "res.json leaks process.env to the API response",
    re: /\bres\.json\s*\(\s*\{[^}]*process\.env\.\w+/g,
    rationale: "Putting process.env into res.json hands every secret in the environment to the caller.",
    fix: "Build a response object that contains only the fields the client needs.",
  },
  {
    id: "nextjs-revalidate-path-user-input",
    severity: "high",
    category: "nextjs",
    confidence: 75,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "revalidatePath called with user-controlled input",
    re: /revalidatePath\s*\(\s*[^)]*\b(?:req\.|request\.|params\.|searchParams|body\.)/g,
    rationale: "An attacker can force the cache to be busted on arbitrary paths, enabling DoS or cache-poisoning side effects.",
    fix: "Validate the path against an allowlist before calling revalidatePath.",
  },
  {
    id: "nextjs-revalidate-tag-user-input",
    severity: "high",
    category: "nextjs",
    confidence: 75,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "revalidateTag called with user-controlled input",
    re: /revalidateTag\s*\(\s*[^)]*\b(?:req\.|request\.|params\.|searchParams|body\.)/g,
    rationale: "Letting the user pick which cache tag to invalidate enables targeted cache poisoning and DoS.",
    fix: "Restrict tag names to a fixed allowlist before calling revalidateTag.",
  },
  {
    id: "nextjs-middleware-no-matcher",
    severity: "medium",
    category: "nextjs",
    confidence: 60,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "middleware.ts missing config.matcher (matches every route)",
    re: /export\s+(?:async\s+)?function\s+middleware\s*\([\s\S]*?\}(?![\s\S]*export\s+const\s+config)/g,
    rationale: "Without a matcher, the middleware runs on every request including static assets. Bugs there can break or expose the whole app.",
    fix: "Export `const config = { matcher: [...] }` to scope middleware to the routes that need it.",
  },
  {
    id: "nextjs-getserversideprops-leak-env",
    severity: "critical",
    category: "nextjs",
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "getServerSideProps returns process.env into props",
    re: /getServerSideProps[\s\S]{0,400}return\s*\{\s*props\s*:\s*\{[^}]*process\.env\.\w+/g,
    rationale: "Anything in `props` is serialized into the HTML and shipped to the browser. Server secrets land in page source.",
    fix: "Only return data the page needs. Never put process.env values into props.",
  },
  {
    id: "nextjs-getstaticprops-leak-env",
    severity: "critical",
    category: "nextjs",
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "getStaticProps returns process.env into props",
    re: /getStaticProps[\s\S]{0,400}return\s*\{\s*props\s*:\s*\{[^}]*process\.env\.\w+/g,
    rationale: "Static props are baked into the HTML at build time. Including process.env leaks secrets into the public bundle.",
    fix: "Strip server-only env vars from the props object.",
  },
];
