import type { CodeRule } from "../engines/code-rules.js";

export const NODEJS_RULES: CodeRule[] = [
  {
    id: "node-vm-runincontext-user",
    severity: "critical",
    category: "nodejs",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "vm.runInNewContext / runInThisContext with request input",
    re: /\bvm\s*\.\s*(?:runInNewContext|runInThisContext|runInContext|compileFunction)\s*\((?:[\s\S]{0,200}?)(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "Node's vm module is not a security boundary. User code in a vm context can break out via prototype walks (constructor.constructor) and reach the host process.",
    fix: "Do not run untrusted code. If you must isolate workloads, use a separate process with seccomp/landlock or a real sandbox (isolated-vm with strict resource limits).",
  },
  {
    id: "node-vm2-import",
    severity: "high",
    category: "nodejs",
    confidence: 95,
    owasp: "A06:2021 Vulnerable and Outdated Components",
    languages: ["javascript", "typescript"],
    title: "vm2 sandbox library import (deprecated, sandbox-escape vulns)",
    re: /\b(?:require|from)\s*\(?\s*['"]vm2['"]/g,
    rationale: "vm2 was discontinued in 2023 with multiple unpatched sandbox-escape CVEs (CVE-2023-37466 etc). Any escape gives full host RCE.",
    fix: "Migrate to isolated-vm or run untrusted code in a separate OS process with restricted privileges.",
  },
  {
    id: "node-worker-eval-true",
    severity: "critical",
    category: "nodejs",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "new Worker(string, { eval: true }) — string treated as code", // ironward-ignore
    re: /\bnew\s+Worker\s*\([^)]*,\s*\{[^}]*\beval\s*:\s*true/g, // ironward-ignore
    rationale: "With eval: true, the Worker constructor's first argument is compiled and executed as JavaScript on a worker thread.",
    fix: "Set eval: false (the default). Pass a file path to the worker script. Send data via workerData / postMessage.",
  },
  {
    id: "node-prototype-pollution-object-assign",
    severity: "high",
    category: "prototype-pollution",
    confidence: 80,
    owasp: "A08:2021 Software and Data Integrity Failures",
    languages: ["javascript", "typescript"],
    title: "Object.assign({}, req.body) without key allowlist", // ironward-ignore
    re: /\bObject\s*\.\s*assign\s*\(\s*\{\s*\}\s*,\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g, // ironward-ignore
    rationale: "Direct Object.assign of the request body lets an attacker set __proto__ or constructor keys, polluting Object.prototype across the process.",
    fix: "Validate the body against a Zod/Joi schema first, then assign only allowlisted fields.",
  },
  {
    id: "node-lodash-set-user-key",
    severity: "high",
    category: "prototype-pollution",
    confidence: 85,
    owasp: "A08:2021 Software and Data Integrity Failures",
    languages: ["javascript", "typescript"],
    title: "lodash.set / setWith with a user-controlled key path",
    re: /\b(?:_|lodash)\s*\.\s*(?:set|setWith)\s*\([^,]+,\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "lodash.set walks an arbitrary path string; '__proto__.isAdmin' from the user pollutes Object.prototype.",
    fix: "Use a fixed path string and assign user values to leaves only, after schema validation.",
  },
  {
    id: "node-json-parse-user-no-reviver",
    severity: "low",
    category: "prototype-pollution",
    confidence: 50,
    owasp: "A08:2021 Software and Data Integrity Failures",
    languages: ["javascript", "typescript"],
    title: "JSON.parse on user input without a __proto__-stripping reviver",
    re: /\bJSON\s*\.\s*parse\s*\(\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)\s*\.[A-Za-z_$][\w]*\s*\)/g,
    rationale: "Parsed objects retain a __proto__ key as a data property; if downstream code merges or assigns from this object, prototype pollution becomes possible.",
    fix: "Pass a reviver that drops __proto__ and constructor keys, or feed the parsed object through a schema validator that strips unknown keys.",
  },
  {
    id: "node-regex-redos-nested-quantifier",
    severity: "medium",
    category: "dangerous-function",
    confidence: 75,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Regex with nested quantifier (catastrophic backtracking / ReDoS)",
    re: /\/[^/\n]*\([^)]*[+*]\)[+*][^/\n]*\/[gimsuy]*/g,
    rationale: "Patterns like (a+)+ or (.*)* take exponential time on adversarial input — a few KB of input can pin a Node event-loop CPU for hours.",
    fix: "Rewrite the regex to be linear (atomic groups via (?>...) or possessive quantifiers in supported engines). Or use a regex engine with a hard timeout (re2).",
  },
  {
    id: "node-regex-catastrophic-alternation",
    severity: "medium",
    category: "dangerous-function",
    confidence: 70,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Regex with overlapping alternation under a quantifier (ReDoS)",
    re: /\/[^/\n]*\(([A-Za-z0-9])\|\1\|\1\)[+*][^/\n]*\/[gimsuy]*/g,
    rationale: "Alternations like (a|a|a)* let the engine choose multiple parse paths for the same input — exponential backtracking on failure.",
    fix: "Deduplicate the alternation. If you genuinely need alternation, anchor it and use a non-backtracking engine (re2).",
  },
  {
    id: "node-http-request-user-host",
    severity: "high",
    category: "ssrf",
    confidence: 80,
    owasp: "A10:2021 Server-Side Request Forgery",
    languages: ["javascript", "typescript"],
    title: "http.request / https.request with user-supplied host (SSRF)",
    re: /\bhttps?\s*\.\s*request\s*\(\s*\{[^}]*\bhost(?:name)?\s*:\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "User control of the host lets attackers reach internal services (cloud metadata at 169.254.169.254, internal admin panels) and exfiltrate data.",
    fix: "Resolve the hostname, reject private/loopback/link-local CIDRs, and check against an allowlist before issuing the request.",
  },
  {
    id: "node-dns-lookup-then-fetch",
    severity: "medium",
    category: "ssrf",
    confidence: 65,
    owasp: "A10:2021 Server-Side Request Forgery",
    languages: ["javascript", "typescript"],
    title: "dns.lookup with user input followed by fetch (DNS rebinding window)",
    re: /\bdns\s*\.\s*lookup\s*\(\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "Resolving a user host then fetching from the resolved IP creates a TOCTOU/DNS-rebinding window — the attacker's domain can flip to 127.0.0.1 between checks.",
    fix: "Resolve once, validate the IP is public, and pass the literal IP to fetch with a Host header. Or use a resolver wrapper that pins the IP for the request.",
  },
  {
    id: "node-buffer-allocunsafe-user-size",
    severity: "high",
    category: "unsafe-io",
    confidence: 85,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "Buffer.allocUnsafe with user-supplied size (uninitialized memory)",
    re: /\bBuffer\s*\.\s*allocUnsafe(?:Slow)?\s*\(\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "allocUnsafe returns memory that has NOT been zeroed. Sending the buffer back to the client (or writing it to a file) leaks whatever was previously in that heap region — secrets, other users' data.",
    fix: "Use Buffer.alloc(size) which zero-fills, or call buf.fill(0) before any read of an allocUnsafe buffer.",
  },
  {
    id: "node-process-binding",
    severity: "medium",
    category: "dangerous-function",
    confidence: 70,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "process.binding() — internal/deprecated API",  // ironward-ignore
    re: /\bprocess\s*\.\s*binding\s*\(/g,
    rationale: "process.binding exposes internal C++ bindings that bypass the public API. It is deprecated and historically a source of sandbox-escape and deprecation issues.",
    fix: "Use the documented public Node API equivalent. Remove process.binding entirely.",
  },
  {
    id: "node-tls-reject-unauthorized-false",
    severity: "high",
    category: "insecure-protocol",
    confidence: 95,
    owasp: "A07:2021 Identification and Authentication Failures",
    languages: ["javascript", "typescript"],
    title: "rejectUnauthorized: false disables TLS certificate validation",  // ironward-ignore
    re: /\brejectUnauthorized\s*:\s*false\b/g,
    rationale: "Disabling certificate validation means any MITM with a self-signed cert can intercept the connection. TLS becomes obfuscation, not authentication.",
    fix: "Remove the option (default is true). For self-signed dev certs, add the CA to NODE_EXTRA_CA_CERTS instead.",
  },
  {
    id: "node-axios-https-agent-insecure",
    severity: "high",
    category: "insecure-protocol",
    confidence: 90,
    owasp: "A07:2021 Identification and Authentication Failures",
    languages: ["javascript", "typescript"],
    title: "axios httpsAgent configured to skip TLS verification",
    re: /\bnew\s+https\s*\.\s*Agent\s*\(\s*\{[^}]*rejectUnauthorized\s*:\s*false/g,
    rationale: "Same as rejectUnauthorized: false on a fetch — any on-path attacker can MITM the connection.",  // ironward-ignore
    fix: "Drop the option. Pin the CA via ca: fs.readFileSync(...) if you really need a custom trust store.",
  },
  {
    id: "node-tls-reject-env-zero",
    severity: "critical",
    category: "insecure-protocol",
    confidence: 99,
    owasp: "A07:2021 Identification and Authentication Failures",
    languages: ["javascript", "typescript"],
    title: "NODE_TLS_REJECT_UNAUTHORIZED set to '0' disables TLS for the whole process",
    re: /\bNODE_TLS_REJECT_UNAUTHORIZED\s*[:=]\s*['"]?0['"]?/g,
    rationale: "Setting this env var disables TLS certificate validation globally — every outgoing TLS connection is vulnerable to MITM.",
    fix: "Remove the assignment. Use proper CA configuration or NODE_EXTRA_CA_CERTS for dev certs.",
  },
  {
    id: "node-create-cipher-no-iv",
    severity: "high",
    category: "weak-crypto",
    confidence: 95,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["javascript", "typescript"],
    title: "crypto.createCipher (deprecated, no IV, derives weak key)",  // ironward-ignore
    re: /\bcrypto\s*\.\s*createCipher\s*\(/g,
    rationale: "createCipher derives an IV and key from the passphrase via MD5, with no salt and no IV input. Identical plaintexts encrypt identically and the KDF is broken.",
    fix: "Use crypto.createCipheriv with a 12-byte random IV (GCM) and a key from a proper KDF (scrypt or PBKDF2).",
  },
  {
    id: "node-runtime-npm-install-user",
    severity: "critical",
    category: "dangerous-function",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "Spawning npm/yarn/pnpm install at runtime with user-controlled name",
    re: /\b(?:exec|execSync|spawn|spawnSync|execFile)\s*\(\s*['"](?:npm|yarn|pnpm|bun)['"]\s*,\s*\[[^\]]*['"]install['"][\s\S]{0,150}?(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "Installing a user-named package downloads and executes arbitrary postinstall scripts in your service — direct RCE via the npm registry.",
    fix: "Never install user input. If you must support plugins, ship a fixed allowlist and pin versions in package.json.",
  },
  {
    id: "node-fetch-disable-redirect-bypass",
    severity: "medium",
    category: "ssrf",
    confidence: 60,
    owasp: "A10:2021 Server-Side Request Forgery",
    languages: ["javascript", "typescript"],
    title: "follow-redirects / fetch with redirect: 'follow' to a user URL",
    re: /\bfetch\s*\(\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)\s*\.[A-Za-z_$][\w]*\s*,\s*\{[^}]*redirect\s*:\s*['"]follow['"]/g,
    rationale: "Following redirects on a user URL lets the attacker bounce from a public host to an internal one (allowlist bypass).",
    fix: "Set redirect: 'manual' and validate each Location hop against the allowlist before re-issuing.",
  },
  {
    id: "node-fs-symlink-user-input",
    severity: "medium",
    category: "unsafe-io",
    confidence: 75,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "fs.symlink / fs.symlinkSync target from request input",
    re: /\bfs\s*\.\s*symlink(?:Sync)?\s*\(\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "User-controlled symlink targets enable arbitrary-file disclosure or overwrite when the symlink is later read or written.",
    fix: "Resolve the target inside a safe base directory and refuse links pointing outside it.",
  },
  {
    id: "node-dynamic-import-user",
    severity: "high",
    category: "dangerous-function",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "Dynamic import() with request input",
    re: /\bimport\s*\(\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query|headers)/g,
    rationale: "Dynamic import of an attacker-controlled path can load arbitrary files from disk and execute their top-level code.",
    fix: "Map user values to a fixed allowlist of module paths. Only import the mapped value.",
  },
];
