import type { CodeRule } from "../engines/code-rules.js";

export const PRISMA_RULES: CodeRule[] = [
  {
    id: "prisma-queryraw-template-req",
    severity: "critical",
    category: "prisma-drizzle",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "prisma.$queryRaw template string interpolates request data",
    re: /\$queryRaw\s*`[^`]*\$\{[^}]*\b(?:req|request|params|searchParams|body|query)\b[^}]*\}/g,
    rationale: "Although $queryRaw is parameterized when used as a tagged template, interpolating raw user input into the template can still introduce SQL injection if values are concatenated as identifiers or expressions.",
    fix: "Use Prisma's typed query builder (findMany / where / etc.) or pass values as parameters via Prisma.sql, never as identifiers.",
  },
  {
    id: "prisma-executeraw-template-req",
    severity: "critical",
    category: "prisma-drizzle",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "prisma.$executeRaw template string interpolates request data",
    re: /\$executeRaw\s*`[^`]*\$\{[^}]*\b(?:req|request|params|searchParams|body|query)\b[^}]*\}/g,
    rationale: "Mixing user input into a raw SQL template runs the risk of SQL injection through identifier or expression slots.",
    fix: "Use the typed Prisma client (update / delete) or Prisma.sql with parameterized values.",
  },
  {
    id: "prisma-queryrawunsafe-user-input",
    severity: "critical",
    category: "prisma-drizzle",
    confidence: 95,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "prisma.$queryRawUnsafe with user input",
    re: /\$queryRawUnsafe\s*\([^)]*\b(?:req|request|params|searchParams|body|query|input)\b/g,
    rationale: "$queryRawUnsafe concatenates strings with no parameterization. Passing any user input is direct SQL injection.",
    fix: "Switch to $queryRaw with a tagged template, or use Prisma's typed query API.",
  },
  {
    id: "prisma-executerawunsafe-user-input",
    severity: "critical",
    category: "prisma-drizzle",
    confidence: 95,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "prisma.$executeRawUnsafe with user input",
    re: /\$executeRawUnsafe\s*\([^)]*\b(?:req|request|params|searchParams|body|query|input)\b/g,
    rationale: "$executeRawUnsafe runs the supplied SQL with no parameterization, so any user-controlled value is a SQL injection.",
    fix: "Use $executeRaw with parameterized templates or the typed Prisma API.",
  },
  {
    id: "prisma-findunique-no-ownership",
    severity: "high",
    category: "prisma-drizzle",
    confidence: 60,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "prisma.findUnique by id without an ownership filter",
    re: /\.findUnique\s*\(\s*\{\s*where\s*:\s*\{\s*id\s*:[^}]*\}\s*\}\s*\)/g,
    rationale: "Looking up a record only by id lets any signed-in user fetch any record by guessing ids. Insecure direct object reference.",
    fix: "Add userId / ownerId / orgId to the where clause so the query only returns rows the caller owns.",  // ironward-ignore
  },
  {
    id: "prisma-findfirst-no-ownership",
    severity: "high",
    category: "prisma-drizzle",
    confidence: 55,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "prisma.findFirst by id without an ownership filter",
    re: /\.findFirst\s*\(\s*\{\s*where\s*:\s*\{\s*id\s*:[^}]*\}\s*\}\s*\)/g,
    rationale: "findFirst by id only is a classic IDOR pattern: any user can guess ids and read others' rows.",
    fix: "Filter by userId / orgId in addition to id.",  // ironward-ignore
  },
  {
    id: "prisma-update-no-ownership",
    severity: "critical",
    category: "prisma-drizzle",
    confidence: 65,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "prisma.update by id without an ownership filter",
    re: /\.update\s*\(\s*\{\s*where\s*:\s*\{\s*id\s*:[^}]*\}\s*,/g,
    rationale: "Updating a record only by id allows any user to modify any other user's row by tampering with the id.",
    fix: "Use updateMany with where: { id, userId } or check ownership before updating.",
  },
  {
    id: "prisma-delete-no-ownership",
    severity: "critical",
    category: "prisma-drizzle",
    confidence: 70,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "prisma.delete by id without an ownership filter",
    re: /\.delete\s*\(\s*\{\s*where\s*:\s*\{\s*id\s*:[^}]*\}\s*\}\s*\)/g,
    rationale: "Delete by id only lets a user delete any row by guessing ids — an IDOR with destructive impact.",
    fix: "Use deleteMany with where: { id, userId } or check ownership before deleting.",
  },
  {
    id: "drizzle-sql-template-user-input",
    severity: "critical",
    category: "prisma-drizzle",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "drizzle sql template interpolates user input as a raw fragment",
    re: /\bsql\s*`[^`]*\$\{[^}]*\b(?:req|request|params|searchParams|body|query)\b[^}]*\}/g,
    rationale: "Drizzle's sql tag parameterizes values but interpolating identifiers or fragments built from user input opens SQL injection.",
    fix: "Pass user values as parameters; never build identifiers or raw fragments from request data.",
  },
  {
    id: "drizzle-db-execute-req",
    severity: "critical",
    category: "prisma-drizzle",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "drizzle db.execute(sql`...`) embeds user input",
    re: /\bdb\.execute\s*\(\s*sql\s*`[^`]*\$\{[^}]*\b(?:req|request|params|searchParams|body|query)\b/g,
    rationale: "db.execute runs raw SQL. Mixing user-controlled values into the template can result in SQL injection if interpolated as a fragment.",
    fix: "Use the query builder, or pass parameters via the sql tag without embedding raw user fragments.",
  },
  {
    id: "drizzle-eq-id-no-userid",
    severity: "high",
    category: "prisma-drizzle",
    confidence: 55,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "drizzle eq(table.id, req.params.id) without and(eq(table.userId, ...))",
    re: /\beq\s*\([^,]+\.id\s*,\s*(?:req|request|ctx|params|searchParams)\.[\w.]+\s*\)(?![\s\S]{0,200}and\s*\([\s\S]{0,200}userId)/g,
    rationale: "Filtering only by id and a request value is the textbook IDOR pattern.",
    fix: "Wrap in and(eq(table.id, x), eq(table.userId, currentUserId)) so only the owner can read the row.",
  },
  {
    id: "drizzle-where-eq-id-only",
    severity: "high",
    category: "prisma-drizzle",
    confidence: 55,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "drizzle .where(eq(table.id, ...)) with no ownership condition",  // ironward-ignore
    re: /\.where\s*\(\s*eq\s*\([^,]+\.id\s*,\s*[^)]+\)\s*\)/g,
    rationale: "where(eq(table.id, x)) alone returns the row regardless of who owns it.",
    fix: "Use where(and(eq(table.id, x), eq(table.userId, currentUserId))).",
  },
  {
    id: "prisma-findmany-no-take",
    severity: "medium",
    category: "prisma-drizzle",
    confidence: 50,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "prisma.findMany without take/limit (mass extraction risk)",
    re: /\.findMany\s*\(\s*(?:\{(?:[^{}]|\{[^{}]*\})*\}\s*)?\)/g,
    rationale: "findMany with no take returns the entire table, which can hammer the DB and leak more data than intended if combined with weak filtering.",
    fix: "Always set `take: <reasonable limit>` and use cursor-based pagination for large tables.",
  },
  {
    id: "prisma-create-spread-body",
    severity: "high",
    category: "prisma-drizzle",
    confidence: 70,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "prisma.create({ data: { ...req.body } }) - mass assignment",  // ironward-ignore
    re: /\.create\s*\(\s*\{\s*data\s*:\s*\{\s*\.\.\.\s*(?:req|request|ctx)\.(?:body|params|query)/g,
    rationale: "Spreading the request body into create lets a caller set protected fields like role, isAdmin, or userId.",
    fix: "Pick fields explicitly (e.g. data: { name: req.body.name, userId: session.user.id }).",
  },
  {
    id: "prisma-update-spread-body",
    severity: "high",
    category: "prisma-drizzle",
    confidence: 70,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "prisma.update({ data: { ...req.body } }) - mass assignment",  // ironward-ignore
    re: /\.update\s*\(\s*\{[^}]*data\s*:\s*\{\s*\.\.\.\s*(?:req|request|ctx)\.(?:body|params|query)/g,
    rationale: "Spreading the request body into update allows a caller to overwrite fields they should not control.",
    fix: "Whitelist updatable fields explicitly.",
  },
];
