import type { CodeRule } from "../engines/code-rules.js";

export const PYTHON_RULES: CodeRule[] = [
  {
    id: "py-eval-user-input",
    severity: "critical",
    category: "python",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["python"],
    title: "Python eval() with f-string, concat, or request input", // ironward-ignore
    re: /(?<![A-Za-z0-9_.])eval\s*\(\s*(?:f['"]|request\s*\.|flask\s*\.\s*request\s*\.|[A-Za-z_][\w]*\s*\+)/g, // ironward-ignore
    rationale: "Python's eval compiles and runs the argument as code. Any user value reaching it is RCE.",
    fix: "Use ast.literal_eval for literals, or a dispatch dict mapping names to safe functions.",
  },
  {
    id: "py-marshal-loads",
    severity: "critical",
    category: "python",
    confidence: 90,
    owasp: "A08:2021 Software and Data Integrity Failures",
    languages: ["python"],
    title: "marshal.loads on user input",
    re: /\bmarshal\s*\.\s*loads?\s*\(/g,
    rationale: "marshal is for internal CPython bytecode serialization. Loading attacker-controlled marshal data crashes the interpreter or executes code.",
    fix: "Use json or msgpack for cross-trust deserialization. Never marshal across a trust boundary.",
  },
  {
    id: "py-shelve-user-filename",
    severity: "high",
    category: "python",
    confidence: 80,
    owasp: "A08:2021 Software and Data Integrity Failures",
    languages: ["python"],
    title: "shelve.open with user-controlled filename",
    re: /\bshelve\s*\.\s*open\s*\(\s*(?:request\s*\.|flask\s*\.\s*request\s*\.|f['"])/g,
    rationale: "shelve uses pickle under the hood and reads from the given path. Attacker-controlled file or content yields pickle-deserialization RCE.",
    fix: "Pin the shelve path to a server-controlled location and never let user input choose it.",
  },
  {
    id: "py-sql-fstring",
    severity: "critical",
    category: "python",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["python"],
    title: "SQL built via f-string",
    re: /\bf['"][^'"]*\b(?:SELECT|INSERT\s+INTO|UPDATE|DELETE\s+FROM)\b[^'"]*\{[^}]+\}/gi,
    rationale: "Interpolating values into SQL via f-strings is classic SQL injection. Parameters must be bound by the driver, not formatted into the string.",
    fix: "Use parameterized queries: cursor.execute('SELECT * FROM t WHERE id = %s', (user_id,)).",
  },
  {
    id: "py-sql-percent-format",
    severity: "critical",
    category: "python",
    confidence: 88,
    owasp: "A03:2021 Injection",
    languages: ["python"],
    title: "SQL built with % string formatting",
    re: /\bcursor\s*\.\s*execute\s*\(\s*['"][^'"]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b[^'"]*['"]\s*%\s*/gi,
    rationale: "Building SQL with % formatting concatenates user input into the query — same injection risk as f-strings.",
    fix: "Pass parameters as the second argument: cursor.execute('... WHERE id = %s', (id,)).",
  },
  {
    id: "py-sql-format-method",
    severity: "critical",
    category: "python",
    confidence: 88,
    owasp: "A03:2021 Injection",
    languages: ["python"],
    title: "SQL built with str.format()",
    re: /\b['"][^'"]*\b(?:SELECT|INSERT\s+INTO|UPDATE|DELETE\s+FROM)\b[^'"]*\{[^}]*\}[^'"]*['"]\s*\.\s*format\s*\(/gi,
    rationale: ".format() concatenates values into the SQL string — drivers cannot bind these as parameters.",
    fix: "Use the driver's parameter substitution (%s placeholders + tuple of values).",
  },
  {
    id: "py-open-user-path",
    severity: "high",
    category: "path-traversal",
    confidence: 85,
    owasp: "A01:2021 Broken Access Control",
    languages: ["python"],
    title: "open() called with request input as the path",
    re: /\bopen\s*\(\s*(?:request\s*\.\s*(?:args|form|json|values|files)|flask\s*\.\s*request\s*\.\s*(?:args|form|json|values))/g,
    rationale: "Reading or writing a file at a user-supplied path enables directory traversal (../../etc/passwd, /proc/self/environ).",
    fix: "Resolve the path against a safe base directory with os.path.realpath and check it stays inside that base.",
  },
  {
    id: "py-os-system-user",
    severity: "critical",
    category: "python",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["python"],
    title: "os.system() with user input",
    re: /\bos\s*\.\s*system\s*\(\s*(?:request\s*\.|flask\s*\.\s*request\s*\.|f['"])/g,
    rationale: "os.system runs the argument through /bin/sh — any concatenated user input is command injection.",
    fix: "Use subprocess.run with a list of args and shell=False (the default).",
  },
  {
    id: "py-os-popen-user",
    severity: "critical",
    category: "python",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["python"],
    title: "os.popen() with user input",
    re: /\bos\s*\.\s*popen\s*\(\s*(?:request\s*\.|flask\s*\.\s*request\s*\.|f['"])/g,
    rationale: "os.popen pipes through the shell — same injection class as os.system.",
    fix: "Use subprocess.Popen with a list of args and shell=False.",
  },
  {
    id: "py-subprocess-user-argv0",
    severity: "high",
    category: "python",
    confidence: 75,
    owasp: "A03:2021 Injection",
    languages: ["python"],
    title: "subprocess.run/Popen with request input as the executable path",
    re: /\bsubprocess\s*\.\s*(?:run|Popen|call|check_output|check_call)\s*\(\s*\[\s*(?:request\s*\.|flask\s*\.\s*request\s*\.|f['"])/g,
    rationale: "Even with shell=False, letting the user pick the executable lets them run any binary on PATH.",
    fix: "Pin argv[0] to a fixed binary path. Validate any user-supplied flags against an allowlist.",
  },
  {
    id: "py-tempfile-mktemp",
    severity: "medium",
    category: "python",
    confidence: 95,
    owasp: "A04:2021 Insecure Design",
    languages: ["python"],
    title: "tempfile.mktemp() — race condition (deprecated)",  // ironward-ignore
    re: /\btempfile\s*\.\s*mktemp\s*\(/g,
    rationale: "mktemp returns a filename without creating the file. An attacker can win the race and create a symlink at that path before you open it.",
    fix: "Use tempfile.mkstemp() (returns an open fd atomically) or NamedTemporaryFile.",
  },
  {
    id: "py-md5-sha1-password",
    severity: "high",
    category: "weak-crypto",
    confidence: 85,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["python"],
    title: "hashlib.md5/sha1 used for password hashing",
    re: /\bhashlib\s*\.\s*(?:md5|sha1)\s*\([^)]*(?:password|passwd|pwd)/gi, // ironward-ignore
    rationale: "MD5 and SHA-1 are unsalted, fast hashes — designed for speed. A modern GPU brute-forces billions per second.",
    fix: "Use bcrypt, argon2, or scrypt with appropriate work factors. Never use plain hash functions for passwords.",
  },
  {
    id: "py-django-orm-extra-where",
    severity: "high",
    category: "python",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["python"],
    title: "Django QuerySet.extra(where=...) with user input",
    re: /\.extra\s*\(\s*where\s*=\s*\[/g,
    rationale: "extra(where=...) embeds raw SQL fragments into the generated query. User input here is direct SQL injection.",
    fix: "Use Q() expressions, ORM filter() lookups, or RawSQL with bound params.",
  },
  {
    id: "py-django-raw-sql-concat",
    severity: "critical",
    category: "python",
    confidence: 90,
    owasp: "A03:2021 Injection",
    languages: ["python"],
    title: "Django Manager.raw() with string concatenation",
    re: /\.raw\s*\(\s*['"][^'"]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b[^'"]*['"]\s*[+%]/g,
    rationale: "Concatenating into the raw() argument bypasses Django's parameterization — direct SQL injection.",
    fix: "Pass a params list as the second argument: .raw('SELECT ... WHERE id=%s', [id]).",
  },
  {
    id: "py-flask-secret-hardcoded",
    severity: "critical",
    category: "python",
    confidence: 90,
    owasp: "A02:2021 Cryptographic Failures",
    languages: ["python"],
    title: "Flask SECRET_KEY hardcoded to a guessable value", // ironward-ignore
    re: /\bSECRET_KEY\s*=\s*['"](?:dev|change-?me|changeme|secret|password|test|changeit|flask-secret|my-secret|todo)['"]/gi, // ironward-ignore
    rationale: "Flask uses SECRET_KEY to sign session cookies. A guessable key lets attackers forge any user's session.",
    fix: "Read from an env var: app.config['SECRET_KEY'] = os.environ['FLASK_SECRET_KEY']. Generate with secrets.token_hex(32).",
  },
  {
    id: "py-werkzeug-debugger-pin", // ironward-ignore
    severity: "high",
    category: "python",
    confidence: 80,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["python"],
    title: "Werkzeug debugger enabled outside development", // ironward-ignore
    re: /\bWERKZEUG_DEBUG_PIN\s*=\s*['"]?off['"]?/g,
    rationale: "Disabling the debug PIN exposes a Python interactive console on the running web process — instant RCE for anyone reaching the page.",
    fix: "Never disable the PIN. Better: never run the Werkzeug debugger in any environment reachable from outside localhost.", // ironward-ignore
  },
  {
    id: "py-importlib-user-module",
    severity: "high",
    category: "python",
    confidence: 85,
    owasp: "A03:2021 Injection",
    languages: ["python"],
    title: "importlib.import_module with user input",
    re: /\bimportlib\s*\.\s*import_module\s*\(\s*(?:request\s*\.|flask\s*\.\s*request\s*\.|f['"])/g,
    rationale: "Importing a user-named module can pull in arbitrary code from sys.path and execute its top-level statements.",
    fix: "Map user values to a fixed allowlist of module names. Only import the mapped value.",
  },
  {
    id: "py-urllib-urlopen-user",
    severity: "high",
    category: "ssrf",
    confidence: 85,
    owasp: "A10:2021 Server-Side Request Forgery",
    languages: ["python"],
    title: "urllib.request.urlopen with user-supplied URL (SSRF)",
    re: /\burllib\s*\.\s*request\s*\.\s*urlopen\s*\(\s*(?:request\s*\.|flask\s*\.\s*request\s*\.|f['"])/g,
    rationale: "User-controlled URLs let attackers reach internal services (cloud metadata, admin panels).",
    fix: "Resolve the host, block private/loopback CIDRs, and check against an allowlist before calling urlopen.",
  },
  {
    id: "py-requests-verify-false",
    severity: "high",
    category: "insecure-protocol",
    confidence: 95,
    owasp: "A07:2021 Identification and Authentication Failures",
    languages: ["python"],
    title: "requests called with verify=False",
    re: /\brequests\s*\.\s*(?:get|post|put|delete|patch|request|head|options)\s*\([^)]*verify\s*=\s*False/g,
    rationale: "verify=False disables TLS certificate validation. Any on-path attacker with a self-signed cert can MITM the connection.",
    fix: "Remove verify=False. For internal CAs, set verify='/path/to/ca-bundle.pem' or REQUESTS_CA_BUNDLE.",
  },
  {
    id: "py-requests-get-user-url",
    severity: "high",
    category: "ssrf",
    confidence: 80,
    owasp: "A10:2021 Server-Side Request Forgery",
    languages: ["python"],
    title: "requests.get/post with user-supplied URL (SSRF)",
    re: /\brequests\s*\.\s*(?:get|post|put|delete|patch|request|head)\s*\(\s*(?:request\s*\.|flask\s*\.\s*request\s*\.|f['"])/g,
    rationale: "User-controlled URLs let attackers reach internal services and exfiltrate metadata creds.",
    fix: "Validate the host against an allowlist and reject private CIDRs before issuing the request.",
  },
  {
    id: "py-namedtempfile-delete-false",
    severity: "medium",
    category: "python",
    confidence: 70,
    owasp: "A04:2021 Insecure Design",
    languages: ["python"],
    title: "tempfile.NamedTemporaryFile(delete=False) leaves file on disk",  // ironward-ignore
    re: /\btempfile\s*\.\s*NamedTemporaryFile\s*\([^)]*delete\s*=\s*False/g,
    rationale: "delete=False keeps the file after the handle closes. If you forget to unlink, secrets-laden temp files accumulate; in shared /tmp directories, other users may read them.",
    fix: "Use the default delete=True, or unlink explicitly in a finally block. Set the file mode to 0o600 on creation.",
  },
  {
    id: "py-django-allowed-hosts-wildcard",
    severity: "medium",
    category: "python",
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["python"],
    title: "Django ALLOWED_HOSTS contains '*'",
    re: /\bALLOWED_HOSTS\s*=\s*\[\s*['"]\*['"]/g,
    rationale: "ALLOWED_HOSTS = ['*'] disables host-header validation, enabling cache-poisoning and password-reset-token redirection attacks.",  // ironward-ignore
    fix: "List explicit hostnames: ALLOWED_HOSTS = ['example.com', 'www.example.com'].",
  },
];
