import type { CodeRule } from "../engines/code-rules.js";

export const RATE_LIMITING_RULES: CodeRule[] = [
  {
    id: "rate-limit-missing-register",
    severity: "high",
    category: "rate-limit" as any,
    confidence: 70,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "POST /register|/signup route without rate limiting middleware",
    re: /\bapp\s*\.\s*post\s*\(\s*['"`][^'"`]*\/(?:register|signup)['"`][\s\S]{0,400}?\)/g,
    rationale: "Unlimited /register lets attackers create thousands of accounts (resource exhaustion, spam, fake reviews, captcha-burning).",
    fix: "Wrap the route with `rateLimit({ windowMs: 60_000, max: 5 })` (express-rate-limit) or a per-IP slowDown.",
    negativePattern: /(?:rateLimit|limiter|throttle|slowDown)/,
  },
  {
    id: "rate-limit-missing-password-reset",
    severity: "high",
    category: "rate-limit" as any,
    confidence: 75,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "POST /reset-password|/forgot-password route without rate limiting",
    re: /\bapp\s*\.\s*post\s*\(\s*['"`][^'"`]*\/(?:reset-password|forgot-password)['"`][\s\S]{0,400}?\)/g,
    rationale: "Unlimited password-reset endpoints enable email-bombing of arbitrary users and account-enumeration via timing.",
    fix: "Apply per-IP and per-email rate limits (e.g. 3 / hour / email) before the handler runs.",
    negativePattern: /(?:rateLimit|limiter|throttle|slowDown)/,
  },
  {
    id: "rate-limit-missing-otp",
    severity: "critical",
    category: "rate-limit" as any,
    confidence: 80,
    owasp: "A07:2021 Identification and Authentication Failures",
    languages: ["javascript", "typescript"],
    title: "POST /verify-otp|/2fa endpoint without rate limiting",
    re: /\bapp\s*\.\s*post\s*\(\s*['"`][^'"`]*\/(?:verify-otp|2fa|mfa\/verify)['"`][\s\S]{0,400}?\)/g,
    rationale: "An unlimited OTP / 2FA verification endpoint lets attackers brute-force the 6-digit code (~1M attempts) and bypass second-factor authentication.",
    fix: "Hard-cap attempts per session/user (e.g. 5 tries, then lockout) AND apply per-IP rate limiting.",
    negativePattern: /(?:rateLimit|limiter|throttle|slowDown)/,
  },
  {
    id: "rate-limit-missing-api-key-gen",
    severity: "high",
    category: "rate-limit" as any,
    confidence: 70,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "API-token / api-key generation endpoint without rate limiting",
    re: /\bapp\s*\.\s*post\s*\(\s*['"`][^'"`]*\/(?:api-keys?|api-tokens?|tokens?\/create|generate-(?:key|token))['"`][\s\S]{0,400}?\)/g,
    rationale: "Unlimited token-creation lets a compromised user account exhaust storage and produce thousands of valid credentials that must each be revoked.",
    fix: "Limit to a few tokens per user per hour; consider per-user quotas (max active tokens) in addition to per-IP throttling.",
    negativePattern: /(?:rateLimit|limiter|throttle|slowDown)/,
  },
  {
    id: "rate-limit-missing-magic-link",
    severity: "high",
    category: "rate-limit" as any,
    confidence: 75,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "POST /magic-link|/passwordless endpoint without rate limiting",
    re: /\bapp\s*\.\s*post\s*\(\s*['"`][^'"`]*\/(?:magic-link|passwordless|magiclink)['"`][\s\S]{0,400}?\)/g,
    rationale: "Magic-link endpoints send email and create login tokens. Without rate limiting they enable email-bombing and bulk-token leakage if SMTP logs are exposed.",
    fix: "Cap to ~3 magic-links per email per hour and ~10 per IP per hour.",
    negativePattern: /(?:rateLimit|limiter|throttle|slowDown)/,
  },
];
