import type { CodeRule } from "../engines/code-rules.js";

export const STRIPE_RULES: CodeRule[] = [
  {
    id: "stripe-secret-in-public-env",
    severity: "critical",
    category: "stripe",
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "new Stripe(process.env.NEXT_PUBLIC_STRIPE_*) — secret leaked to client",  // ironward-ignore
    re: /new\s+Stripe\s*\(\s*process\.env\.(?:NEXT_PUBLIC_|VITE_|REACT_APP_)STRIPE/g,
    rationale: "Public env vars ship to the browser bundle. The Stripe secret key grants full account control (charges, refunds, customers).",
    fix: "Use a server-only env (STRIPE_SECRET_KEY) and only construct the Stripe client in server code.",
  },
  {
    id: "stripe-secret-key-literal-live",
    severity: "critical",
    category: "stripe",
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Stripe sk_live_ literal in source",
    re: /\bsk_live_[A-Za-z0-9]{16,}\b/g,
    rationale: "A live secret key in source can be exfiltrated via git history, public repos, or build artifacts.",
    fix: "Rotate the key immediately. Load secrets from env vars or a secret manager.",
  },
  {
    id: "stripe-secret-key-literal-test",
    severity: "high",
    category: "stripe",
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Stripe sk_test_ literal in source",
    re: /\bsk_test_[A-Za-z0-9]{16,}\b/g,
    rationale: "Even test keys can leak customer data and be abused for fraud detection bypass.",
    fix: "Rotate the test key and load it from env vars.",
  },
  {
    id: "stripe-restricted-key-literal",
    severity: "high",
    category: "stripe",
    confidence: 90,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Stripe restricted key (rk_live_) literal in source",
    re: /\brk_live_[A-Za-z0-9]{16,}\b/g,
    rationale: "Restricted keys still grant scoped API access. Hardcoding leaks them to anyone with repo access.",
    fix: "Rotate and store in a secret manager.",
  },
  {
    id: "stripe-webhook-no-construct-event",
    severity: "critical",
    category: "stripe",
    confidence: 80,
    owasp: "A08:2021 Software and Data Integrity Failures",
    languages: ["javascript", "typescript"],
    title: "Stripe webhook handler missing constructEvent signature verification",
    // Match a Next.js POST handler that mentions stripe but doesn't call constructEvent in scope.
    re: /export\s+async\s+function\s+POST\s*\([\s\S]{0,1500}?stripe[\s\S]{0,1000}?\}/g,
    negativePattern: /stripe\.webhooks\.constructEvent/,
    rationale: "Without verifying the Stripe-Signature header via constructEvent, attackers can forge webhook events and trigger fulfillments / refunds.",
    fix: "Call stripe.webhooks.constructEvent(rawBody, sigHeader, endpointSecret) before trusting the payload.",  // ironward-ignore
  },
  {
    id: "stripe-webhook-no-signature-header",
    severity: "high",
    category: "stripe",
    confidence: 70,
    owasp: "A08:2021 Software and Data Integrity Failures",
    languages: ["javascript", "typescript"],
    title: "Stripe webhook handler does not read stripe-signature header",
    // Match the function-scope around constructEvent so we can check whether the signature
    // header is read in the same scope.
    re: /(?:export\s+(?:async\s+)?function|function|const)[\s\S]{0,800}?constructEvent\s*\([^)]*\)/gi,
    negativePattern: /stripe-signature/i,
    rationale: "constructEvent without the stripe-signature header skips verification.",
    fix: "Pass headers['stripe-signature'] to constructEvent.",
  },
  {
    id: "stripe-payment-intent-amount-from-body",
    severity: "critical",
    category: "stripe",
    confidence: 90,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "paymentIntents.create with amount from req.body",
    re: /paymentIntents\.create\s*\(\s*\{[^}]*amount\s*:\s*(?:req|request|ctx|body)\.(?:body\.)?\w+/g,
    rationale: "Letting the client pick the amount means a user can pay $0.01 for any item. Pricing must always be derived server-side.",
    fix: "Look up the price from your database based on a product id, not from the request body.",
  },
  {
    id: "stripe-checkout-line-items-from-body",
    severity: "critical",
    category: "stripe",
    confidence: 90,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "checkout.sessions.create with line_items.price from req.body",
    re: /checkout\.sessions\.create\s*\(\s*\{[\s\S]{0,400}line_items[\s\S]{0,200}price\s*:\s*(?:req|request|ctx|body)\.(?:body\.)?\w+/g,
    rationale: "If the client supplies the Stripe price id, an attacker can pass a $0 price id and check out.",
    fix: "Map a server-side product id to its trusted price id before creating the session.",
  },
  {
    id: "stripe-checkout-amount-from-body",
    severity: "critical",
    category: "stripe",
    confidence: 90,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "checkout session price_data.unit_amount from req.body",
    re: /unit_amount\s*:\s*(?:req|request|ctx|body)\.(?:body\.)?\w+/g,
    rationale: "Unit amount taken from the request body lets the client define the price.",
    fix: "Compute unit_amount on the server based on a trusted product / price record.",
  },
  {
    id: "stripe-confirm-customer-from-body",
    severity: "critical",
    category: "stripe",
    confidence: 80,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "paymentIntents.confirm with customer id from request body",
    re: /paymentIntents\.confirm\s*\([^)]*customer\s*:\s*(?:req|request|ctx|body)\.(?:body\.)?\w+/g,
    rationale: "Trusting the client-supplied customer id lets an attacker charge another user's saved payment method.",
    fix: "Resolve the customer id from the authenticated session, not the request body.",
  },
  {
    id: "stripe-refund-no-auth",
    severity: "critical",
    category: "stripe",
    confidence: 80,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Refund triggered from public endpoint with no auth check",
    // Match the full POST handler scope (function open through refunds.create plus a small tail);
    // negativePattern verifies an auth check appears anywhere in that scope.
    re: /export\s+async\s+function\s+POST\s*\([\s\S]{0,1500}?refunds\.create\s*\([\s\S]{0,500}?\}/g,
    negativePattern: /\b(?:getServerSession|getServerAuthSession|auth\s*\(|currentUser\s*\(|getAuth\s*\(|requireAuth|withAuth|isAuthenticated|protect\s*\()/,
    rationale: "An unauthenticated refund endpoint is a direct cash-out for any caller.",
    fix: "Authenticate the caller and authorize that they own the original charge before refunding.",
  },
  {
    id: "stripe-publishable-key-in-server",
    severity: "low",
    category: "stripe",
    confidence: 50,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "new Stripe(...) called with pk_ publishable key",
    re: /new\s+Stripe\s*\(\s*['"]pk_(?:live|test)_/g,
    rationale: "The server SDK requires a secret key. A publishable key here means the integration won't authenticate API calls and may have been swapped accidentally.",
    fix: "Use STRIPE_SECRET_KEY (sk_) on the server and use the publishable key only in browser-side @stripe/stripe-js.",
  },
  {
    id: "stripe-webhook-secret-default",
    severity: "high",
    category: "stripe",
    confidence: 70,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Stripe webhook endpoint secret defaulted to empty string",
    re: /STRIPE_WEBHOOK_SECRET\s*\|\|\s*['"]['"]/g,
    rationale: "Falling back to '' makes constructEvent succeed for any signature, defeating verification.",
    fix: "Refuse to start if STRIPE_WEBHOOK_SECRET is missing, never default to an empty string.",
  },
  {
    id: "stripe-customer-create-no-userid",
    severity: "medium",
    category: "stripe",
    confidence: 50,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "stripe.customers.create without metadata.userId",
    re: /customers\.create\s*\(\s*\{(?:(?!metadata)[\s\S]){0,300}\}\s*\)/g,
    rationale: "Without a userId in metadata you cannot reliably tie a Stripe customer back to your user, opening the door to billing-account confusion.",
    fix: "Always include metadata: { userId } when creating Stripe customers.",
  },
];
