import type { CodeRule } from "../engines/code-rules.js";

export const SUPABASE_RULES: CodeRule[] = [
  {
    id: "supabase-service-role-frontend",
    severity: "critical",
    category: "supabase",
    confidence: 95,
    owasp: "A05:2021 Security Misconfiguration",
    languages: ["javascript", "typescript"],
    title: "Supabase service_role key exposed in frontend / NEXT_PUBLIC_ env",
    re: /\b(?:NEXT_PUBLIC_SUPABASE_SERVICE_ROLE(?:_KEY)?|VITE_SUPABASE_SERVICE_ROLE(?:_KEY)?|REACT_APP_SUPABASE_SERVICE_ROLE(?:_KEY)?)\b/g, // ironward-ignore
    rationale: "service_role bypasses Row Level Security entirely. NEXT_PUBLIC_/VITE_/REACT_APP_ vars are bundled into the client and visible to any user.",
    fix: "Move the service_role key to a server-only env var (no NEXT_PUBLIC_ prefix). Use the anon key in the browser.",
  },
  {
    id: "supabase-service-role-client-init",
    severity: "critical",
    category: "supabase",
    confidence: 90,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "createClient called with service_role key",
    re: /\bcreateClient\s*\([^)]*(?:service_?role|SERVICE_?ROLE)/g,
    rationale: "If this runs in a browser bundle, the service_role key bypasses RLS and any user can read/write all rows.",
    fix: "Use the anon key on the client. Reserve service_role for server-side handlers (route handlers, edge functions, RPC).",
  },
  {
    id: "supabase-auth-admin-client-side",
    severity: "critical",
    category: "supabase",
    confidence: 95,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "supabase.auth.admin used in client-side code",
    re: /\bsupabase\s*\.\s*auth\s*\.\s*admin\s*\.\s*\w+/g,
    rationale: "auth.admin requires service_role. Calling it from client code means service_role is exposed.",
    fix: "Move admin operations to a server-only API route that authenticates the caller before invoking auth.admin.",
  },
  {
    id: "supabase-storage-public-bucket",
    severity: "high",
    category: "supabase",
    confidence: 85,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Supabase storage bucket created with public: true",
    re: /\bcreateBucket\s*\([^)]*public\s*:\s*true/g,
    rationale: "Public buckets are world-readable by URL. Anything uploaded is exposed to the internet.",
    fix: "Create the bucket private and use signed URLs for time-limited access. Only mark public buckets that hold non-sensitive assets.",
  },
  {
    id: "supabase-select-no-eq-filter",
    severity: "medium",
    category: "supabase",
    confidence: 60,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "supabase.from(...).select('*') without an .eq() / .match() filter",
    re: /\.from\s*\(\s*['"`][\w]+['"`]\s*\)\s*\.\s*select\s*\(\s*['"`]\*['"`]\s*\)\s*(?!\s*\.\s*(?:eq|match|in|filter|or|range|limit|single)\b)/g,
    rationale: "Selecting all columns and all rows returns everything in the table. Without RLS this is an instant data leak; with RLS it is still a sign that ownership filtering was forgotten.",
    fix: "Add .eq('user_id', currentUserId) (or rely on a tight RLS policy on the table) so a query returns only rows the caller may see.",
  },
  {
    id: "supabase-rls-disabled-statement",
    severity: "critical",
    category: "supabase",
    confidence: 95,
    owasp: "A01:2021 Broken Access Control",
    languages: ["sql"],
    title: "ALTER TABLE ... DISABLE ROW LEVEL SECURITY", // ironward-ignore
    // Require ALTER to start the line (after optional whitespace) — keeps the rule from
    // firing on `-- ALTER TABLE ... DISABLE ROW LEVEL SECURITY` SQL comments and
    // `/* ALTER TABLE ... */` block comments. The `m` flag makes `^` match line starts.
    re: /^\s*ALTER\s+TABLE\s+[\w."]+\s+DISABLE\s+ROW\s+LEVEL\s+SECURITY\b/gim,
    rationale: "Disabling RLS means every authenticated request can read and write every row in the table.",
    fix: "Keep RLS enabled. Write specific policies for SELECT/INSERT/UPDATE/DELETE that scope rows by auth.uid().",
  },
  {
    id: "supabase-rls-policy-using-true",
    severity: "critical",
    category: "supabase",
    confidence: 95,
    owasp: "A01:2021 Broken Access Control",
    languages: ["sql"],
    title: "RLS policy with USING (true) — allows everyone",
    re: /\bCREATE\s+POLICY\b[\s\S]{0,200}?\bUSING\s*\(\s*true\s*\)/gi,
    rationale: "USING (true) makes the policy match every row for every user — equivalent to having no RLS at all.",
    fix: "Replace with USING (auth.uid() = user_id) or another ownership check that scopes rows to the caller.",
  },
  {
    id: "supabase-rls-policy-with-check-true",
    severity: "critical",
    category: "supabase",
    confidence: 95,
    owasp: "A01:2021 Broken Access Control",
    languages: ["sql"],
    title: "RLS policy WITH CHECK (true) — accepts any insert/update", // ironward-ignore
    re: /\bCREATE\s+POLICY\b[\s\S]{0,200}?\bWITH\s+CHECK\s*\(\s*true\s*\)/gi,
    rationale: "WITH CHECK (true) lets every caller insert or update any row, including rows owned by other users.",
    fix: "Replace with WITH CHECK (auth.uid() = user_id) so users can only write rows they own.",
  },
  {
    id: "supabase-anon-insert-no-rls",
    severity: "high",
    category: "supabase",
    confidence: 75,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "supabase.from('table').insert(req.body) without auth context", // ironward-ignore
    re: /\.from\s*\(\s*['"`][\w]+['"`]\s*\)\s*\.\s*insert\s*\(\s*(?:req|request|ctx)\s*\.\s*(?:body|params|query)/g,
    rationale: "Inserting raw request data with the anon key relies entirely on RLS being correctly configured for INSERT — easy to forget.",
    fix: "Validate the body against a schema (Zod) and write an explicit RLS INSERT policy gating by auth.uid().",
  },
  {
    id: "supabase-realtime-on-sensitive-table",
    severity: "high",
    category: "supabase",
    confidence: 70,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript", "sql"],
    title: "Supabase Realtime enabled on a sensitive table",
    re: /\b(?:realtime|REALTIME)\b[^\n;]{0,80}\b(?:users|accounts|payments|invoices|sessions|tokens|secrets)\b/g,
    rationale: "Realtime subscriptions stream INSERT/UPDATE/DELETE payloads to subscribed clients. Without strict RLS, an attacker can subscribe and watch every row change.",
    fix: "Disable realtime on tables holding user data, or write strict RLS policies that filter the realtime payload by auth.uid().",
  },
];
