import type { CodeRule } from "../engines/code-rules.js";

export const TRPC_RULES: CodeRule[] = [
  {
    id: "trpc-public-mutation-user-table",
    severity: "critical",
    category: "trpc",
    confidence: 80,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "publicProcedure mutation touching user/payment/admin/order data",
    re: /publicProcedure[\s\S]{0,400}\.mutation\s*\([\s\S]{0,400}\b(?:user|payment|admin|order|invoice|subscription|billing)\b/gi,
    rationale: "publicProcedure has no auth context. Mutations against sensitive tables should require authentication.",
    fix: "Use protectedProcedure (or an admin-only procedure) so the caller is authenticated and authorized first.",
  },
  {
    id: "trpc-mutation-no-input",
    severity: "high",
    category: "trpc",
    confidence: 70,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: ".mutation without preceding .input() validation",
    re: /\bprocedure\s*\.mutation\s*\(/g,
    rationale: "A mutation with no zod / valibot input schema accepts any shape, opening the door to type confusion and unexpected fields.",
    fix: "Add .input(z.object({...})) before .mutation so inputs are validated and trimmed to the expected schema.",
  },
  {
    id: "trpc-procedure-no-session-check",
    severity: "high",
    category: "trpc",
    confidence: 60,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Procedure resolver missing context.session check",
    re: /\.(?:query|mutation)\s*\(\s*(?:async\s*)?\(\s*\{\s*ctx[\s\S]{0,400}\}\s*\)\s*=>\s*\{(?:(?!ctx\.session|ctx\.user|ctx\.auth|requireAuth)[\s\S]){0,400}\}/g,
    rationale: "A resolver that destructures ctx but never reads ctx.session / ctx.user is implicitly trusting the caller.",
    fix: "Check ctx.session / ctx.user at the top of the resolver and throw TRPCError UNAUTHORIZED if absent.",
  },
  {
    id: "trpc-legacy-t-procedure",
    severity: "high",
    category: "trpc",
    confidence: 75,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Use of t.procedure (unprotected) instead of protectedProcedure",  // ironward-ignore
    re: /\bt\.procedure\b(?![\s\S]{0,200}\.use\s*\()/g,
    rationale: "t.procedure is the base, unauthenticated procedure. Using it for app endpoints exposes them publicly.",
    fix: "Define protectedProcedure = t.procedure.use(isAuthed) and use it for any endpoint that requires a session.",
  },
  {
    id: "trpc-router-public-admin",
    severity: "critical",
    category: "trpc",
    confidence: 85,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "createTRPCRouter exposes admin route via publicProcedure",
    re: /createTRPCRouter\s*\(\s*\{[\s\S]{0,800}admin\w*\s*:\s*publicProcedure/g,
    rationale: "Admin endpoints reachable via publicProcedure can be invoked without authentication.",
    fix: "Use adminProcedure (protectedProcedure plus role check) for any admin route.",
  },
  {
    id: "trpc-publicprocedure-delete",  // ironward-ignore
    severity: "critical",
    category: "trpc",
    confidence: 85,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "publicProcedure mutation named delete*",
    re: /publicProcedure[\s\S]{0,300}\.mutation[\s\S]{0,200}\bdelete\w*/gi,
    rationale: "An unauthenticated delete mutation lets anyone wipe data.",
    fix: "Use protectedProcedure (and check ownership) for destructive mutations.",
  },
  {
    id: "trpc-ctx-user-id-trusted-from-input",
    severity: "high",
    category: "trpc",
    confidence: 70,
    owasp: "A01:2021 Broken Access Control",
    languages: ["javascript", "typescript"],
    title: "Resolver uses input.userId instead of ctx.session.user.id",
    re: /input\.userId\b(?![\s\S]{0,200}ctx\.session\.user\.id)/g,
    rationale: "Trusting userId from the request input allows the caller to impersonate any user.",
    fix: "Always derive the user id from ctx.session, never from input.",
  },
  {
    id: "trpc-superjson-no-transformer-input",
    severity: "medium",
    category: "trpc",
    confidence: 55,
    owasp: "A03:2021 Injection",
    languages: ["javascript", "typescript"],
    title: "tRPC mutation without input schema (z.any / unchecked)",
    re: /\.input\s*\(\s*z\.(?:any|unknown)\s*\(\s*\)\s*\)/g,
    rationale: "z.any / z.unknown disables input validation and lets the caller send arbitrary structures.",
    fix: "Define a strict zod schema describing every accepted field.",
  },
  {
    id: "trpc-throw-no-trpc-error",
    severity: "low",
    category: "trpc",
    confidence: 50,
    owasp: "A09:2021 Security Logging and Monitoring Failures",
    languages: ["javascript", "typescript"],
    title: "Resolver throws raw Error instead of TRPCError",
    re: /\.(?:query|mutation)\s*\([\s\S]{0,400}throw\s+new\s+Error\s*\(/g,
    rationale: "Raw errors bypass tRPC's structured error handling and may leak stack traces to clients.",
    fix: "Throw new TRPCError({ code: 'BAD_REQUEST', message: '...' }) so errors are typed and safe to surface.",
  },
  {
    id: "trpc-no-rate-limit-mutation",
    severity: "medium",
    category: "trpc",
    confidence: 45,
    owasp: "A04:2021 Insecure Design",
    languages: ["javascript", "typescript"],
    title: "publicProcedure mutation with no rate-limit middleware",
    re: /publicProcedure(?![\s\S]{0,400}\.use\s*\([\s\S]{0,200}(?:rateLimit|limiter|throttle))[\s\S]{0,400}\.mutation\s*\(/g,
    rationale: "Public mutations without rate limiting are easy abuse vectors (signup spam, brute-force, enumeration).",
    fix: "Apply a rate-limit middleware (.use(rateLimit(...))) to public mutations.",
  },
];
