/**
 * Slack Block Kit message builder + sender for Ironward security findings.
 *
 * Webhook URLs are bearer tokens. They live only in the closure of a single
 * call and are never logged or persisted by this module.
 */

import type { NormalizedFinding } from "../engines/sarif.js";
import type { SlackConfig } from "./config.js";

export interface SlackMessageInput {
  repo: string;
  scannedBy: string;
  scannedAt: Date;
  findings: NormalizedFinding[];
  reportUrl?: string;
}

export interface DigestInput {
  repo: string;
  newFindings: number;
  byCriticalUnresolved: number;
  fixedThisWeek: number;
  scoreCurrent: number;
  scorePrevious: number;
}

export interface SlackSendResult {
  ok: boolean;
  status?: number;
  error?: string;
  /** Number of findings actually emitted (after threshold). 0 means nothing was sent. */
  sent: number;
}

type Threshold = NonNullable<SlackConfig["threshold"]>;

const SEVERITY_RANK: Record<NormalizedFinding["severity"], number> = {
  critical: 5,
  high: 4,
  medium: 3,
  low: 2,
  info: 1,
};

const SEVERITY_EMOJI: Record<NormalizedFinding["severity"], string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🔵",
  info: "⚪",
};

function thresholdRank(t: Threshold | undefined): number {
  const eff = t ?? "high";
  if (eff === "all") return 0;
  return SEVERITY_RANK[eff];
}

/** Filter findings according to the threshold (e.g. "high" → critical+high only). */
export function filterByThreshold(
  findings: NormalizedFinding[],
  threshold?: SlackConfig["threshold"],
): NormalizedFinding[] {
  const min = thresholdRank(threshold);
  if (min === 0) return findings.slice();
  return findings.filter((f) => SEVERITY_RANK[f.severity] >= min);
}

function severityCounts(findings: NormalizedFinding[]) {
  const counts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  for (const f of findings) counts[f.severity]++;
  return counts;
}

function firstLine(s: string): string {
  const i = s.indexOf("\n");
  return (i === -1 ? s : s.slice(0, i)).trim();
}

/** Build a Slack Block Kit message body. Returns the raw object you would POST to a webhook. */
export function buildSlackMessage(
  input: SlackMessageInput,
  threshold?: SlackConfig["threshold"],
): unknown {
  const effective = threshold ?? "high";
  const filtered = filterByThreshold(input.findings, effective);

  if (filtered.length === 0) {
    return {
      blocks: [
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `:white_check_mark: All clear — no findings ≥ ${effective} for ${input.repo}.`,
          },
        },
      ],
    };
  }

  const counts = severityCounts(filtered);
  const top = filtered.slice(0, 5);

  const blocks: unknown[] = [];

  blocks.push({
    type: "header",
    text: { type: "plain_text", text: "🛡️ Ironward Security Alert", emoji: true },
  });

  blocks.push({
    type: "section",
    fields: [
      { type: "mrkdwn", text: `*Repository*\n${input.repo}` },
      { type: "mrkdwn", text: `*Scanned by*\n${input.scannedBy}` },
      { type: "mrkdwn", text: `*Time*\n${input.scannedAt.toISOString()}` },
    ],
  });

  blocks.push({
    type: "section",
    text: {
      type: "mrkdwn",
      text: `🔴 Critical: *${counts.critical}*    🟠 High: *${counts.high}*    🟡 Medium: *${counts.medium}*`,
    },
  });

  blocks.push({ type: "divider" });

  for (const f of top) {
    const emoji = SEVERITY_EMOJI[f.severity];
    const desc = firstLine(f.description || f.title);
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `${emoji} \`${f.file}:${f.line}\` — *${f.title}*\n    ${desc}`,
      },
    });
  }

  if (filtered.length > top.length) {
    blocks.push({
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `…and ${filtered.length - top.length} more finding(s).`,
        },
      ],
    });
  }

  if (input.reportUrl) {
    blocks.push({
      type: "actions",
      elements: [
        {
          type: "button",
          text: { type: "plain_text", text: "View full report", emoji: true },
          url: input.reportUrl,
        },
      ],
    });
  }

  blocks.push({
    type: "context",
    elements: [{ type: "mrkdwn", text: "Generated by Ironward" }],
  });

  return { blocks };
}

export function buildSlackDigest(d: DigestInput): unknown {
  const diff = d.scoreCurrent - d.scorePrevious;
  const sign = diff >= 0 ? "+" : "-";
  const trend = `Security score: *${d.scoreCurrent}/100* (${sign}${Math.abs(diff)} from last week)`;

  return {
    blocks: [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: `🛡️ Ironward Weekly Digest — ${d.repo}`,
          emoji: true,
        },
      },
      {
        type: "section",
        fields: [
          { type: "mrkdwn", text: `*New findings*\n${d.newFindings}` },
          { type: "mrkdwn", text: `*Critical unresolved*\n${d.byCriticalUnresolved}` },
          { type: "mrkdwn", text: `*Fixed this week*\n${d.fixedThisWeek}` },
        ],
      },
      {
        type: "section",
        text: { type: "mrkdwn", text: trend },
      },
      {
        type: "context",
        elements: [{ type: "mrkdwn", text: "Generated by Ironward" }],
      },
    ],
  };
}

/** Posts to a Slack incoming webhook. Graceful: returns { ok: false, error } on network failure — never throws.
 *  Aborts after timeoutMs (default 10s) so a hung upstream can't stall the scan. */
export async function postSlackMessage(
  webhookUrl: string,
  payload: unknown,
  fetchImpl: typeof fetch = fetch,
  timeoutMs = 10_000,
): Promise<{ ok: boolean; status?: number; error?: string }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetchImpl(webhookUrl, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
      signal: controller.signal,
    });
    if (!res.ok) {
      return { ok: false, status: res.status };
    }
    return { ok: true, status: res.status };
  } catch (err) {
    // Anything thrown after the controller aborted is a timeout — covers both
    // native AbortError (real fetch) and mocks that reject with a generic Error.
    if (controller.signal.aborted) {
      return { ok: false, error: "timeout" };
    }
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  } finally {
    clearTimeout(timer);
  }
}

/** High-level: filter + build + post. Returns { ok, sent } where sent=0 means no findings met threshold. */
export async function sendSlackAlert(
  cfg: SlackConfig,
  input: SlackMessageInput,
  fetchImpl: typeof fetch = fetch,
): Promise<SlackSendResult> {
  const filtered = filterByThreshold(input.findings, cfg.threshold);
  if (filtered.length === 0) {
    // Don't waste a webhook on a no-op.
    return { ok: true, sent: 0 };
  }
  const payload = buildSlackMessage(input, cfg.threshold);
  const res = await postSlackMessage(cfg.webhookUrl, payload, fetchImpl);
  return { ...res, sent: filtered.length };
}
